/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosAgentRequest,
  EquosAgent,
  ListEquosAgentsResponse,
  UpdateEquosAgentRequest,
} from '../models/index';
import {
    CreateEquosAgentRequestFromJSON,
    CreateEquosAgentRequestToJSON,
    EquosAgentFromJSON,
    EquosAgentToJSON,
    ListEquosAgentsResponseFromJSON,
    ListEquosAgentsResponseToJSON,
    UpdateEquosAgentRequestFromJSON,
    UpdateEquosAgentRequestToJSON,
} from '../models/index';

export interface AgentControllerArchiveV3Request {
    id: string;
}

export interface AgentControllerCreateV3Request {
    createEquosAgentRequest: CreateEquosAgentRequest;
}

export interface AgentControllerGetByIdV3Request {
    id: string;
}

export interface AgentControllerListV3Request {
    take?: number;
    skip?: number;
    client?: string;
}

export interface AgentControllerUpdateV3Request {
    id: string;
    updateEquosAgentRequest: UpdateEquosAgentRequest;
}

/**
 * 
 */
export class AgentApi extends runtime.BaseAPI {

    /**
     * Delete an Equos Agent. This action is irreversible.
     * @deprecated
     */
    async agentControllerArchiveV3Raw(requestParameters: AgentControllerArchiveV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAgent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling agentControllerArchiveV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/agents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAgentFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Agent. This action is irreversible.
     * @deprecated
     */
    async agentControllerArchiveV3(requestParameters: AgentControllerArchiveV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAgent> {
        const response = await this.agentControllerArchiveV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Equos Agent.
     * @deprecated
     */
    async agentControllerCreateV3Raw(requestParameters: AgentControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAgent>> {
        if (requestParameters['createEquosAgentRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosAgentRequest',
                'Required parameter "createEquosAgentRequest" was null or undefined when calling agentControllerCreateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/agents`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosAgentRequestToJSON(requestParameters['createEquosAgentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAgentFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Agent.
     * @deprecated
     */
    async agentControllerCreateV3(requestParameters: AgentControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAgent> {
        const response = await this.agentControllerCreateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Agent by ID.
     * @deprecated
     */
    async agentControllerGetByIdV3Raw(requestParameters: AgentControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAgent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling agentControllerGetByIdV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/agents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAgentFromJSON(jsonValue));
    }

    /**
     * Get Equos Agent by ID.
     * @deprecated
     */
    async agentControllerGetByIdV3(requestParameters: AgentControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAgent> {
        const response = await this.agentControllerGetByIdV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Agents.
     * @deprecated
     */
    async agentControllerListV3Raw(requestParameters: AgentControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosAgentsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/agents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosAgentsResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Agents.
     * @deprecated
     */
    async agentControllerListV3(requestParameters: AgentControllerListV3Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosAgentsResponse> {
        const response = await this.agentControllerListV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an Equos Agent.
     * @deprecated
     */
    async agentControllerUpdateV3Raw(requestParameters: AgentControllerUpdateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAgent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling agentControllerUpdateV3().'
            );
        }

        if (requestParameters['updateEquosAgentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEquosAgentRequest',
                'Required parameter "updateEquosAgentRequest" was null or undefined when calling agentControllerUpdateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/agents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEquosAgentRequestToJSON(requestParameters['updateEquosAgentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAgentFromJSON(jsonValue));
    }

    /**
     * Update an Equos Agent.
     * @deprecated
     */
    async agentControllerUpdateV3(requestParameters: AgentControllerUpdateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAgent> {
        const response = await this.agentControllerUpdateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
