/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosAvatarRequest,
  EquosAvatar,
  ListEquosAvatarsResponse,
  UpdateEquosAvatarRequest,
} from '../models/index';
import {
    CreateEquosAvatarRequestFromJSON,
    CreateEquosAvatarRequestToJSON,
    EquosAvatarFromJSON,
    EquosAvatarToJSON,
    ListEquosAvatarsResponseFromJSON,
    ListEquosAvatarsResponseToJSON,
    UpdateEquosAvatarRequestFromJSON,
    UpdateEquosAvatarRequestToJSON,
} from '../models/index';

export interface AvatarControllerArchiveV3Request {
    id: string;
}

export interface AvatarControllerCreateV3Request {
    createEquosAvatarRequest: CreateEquosAvatarRequest;
}

export interface AvatarControllerGetByIdV3Request {
    id: string;
}

export interface AvatarControllerListV3Request {
    take?: number;
    skip?: number;
    client?: string;
}

export interface AvatarControllerUpdateV3Request {
    id: string;
    updateEquosAvatarRequest: UpdateEquosAvatarRequest;
}

/**
 * 
 */
export class AvatarApi extends runtime.BaseAPI {

    /**
     * Delete an Equos Avatar. This action is irreversible.
     * @deprecated
     */
    async avatarControllerArchiveV3Raw(requestParameters: AvatarControllerArchiveV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAvatar>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling avatarControllerArchiveV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/avatars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAvatarFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Avatar. This action is irreversible.
     * @deprecated
     */
    async avatarControllerArchiveV3(requestParameters: AvatarControllerArchiveV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAvatar> {
        const response = await this.avatarControllerArchiveV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Equos Avatar.
     * @deprecated
     */
    async avatarControllerCreateV3Raw(requestParameters: AvatarControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAvatar>> {
        if (requestParameters['createEquosAvatarRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosAvatarRequest',
                'Required parameter "createEquosAvatarRequest" was null or undefined when calling avatarControllerCreateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/avatars`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosAvatarRequestToJSON(requestParameters['createEquosAvatarRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAvatarFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Avatar.
     * @deprecated
     */
    async avatarControllerCreateV3(requestParameters: AvatarControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAvatar> {
        const response = await this.avatarControllerCreateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Avatar by ID.
     * @deprecated
     */
    async avatarControllerGetByIdV3Raw(requestParameters: AvatarControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAvatar>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling avatarControllerGetByIdV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/avatars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAvatarFromJSON(jsonValue));
    }

    /**
     * Get Equos Avatar by ID.
     * @deprecated
     */
    async avatarControllerGetByIdV3(requestParameters: AvatarControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAvatar> {
        const response = await this.avatarControllerGetByIdV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Avatars.
     * @deprecated
     */
    async avatarControllerListV3Raw(requestParameters: AvatarControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosAvatarsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/avatars`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosAvatarsResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Avatars.
     * @deprecated
     */
    async avatarControllerListV3(requestParameters: AvatarControllerListV3Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosAvatarsResponse> {
        const response = await this.avatarControllerListV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an Equos Avatar.
     * @deprecated
     */
    async avatarControllerUpdateV3Raw(requestParameters: AvatarControllerUpdateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosAvatar>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling avatarControllerUpdateV3().'
            );
        }

        if (requestParameters['updateEquosAvatarRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEquosAvatarRequest',
                'Required parameter "updateEquosAvatarRequest" was null or undefined when calling avatarControllerUpdateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/avatars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEquosAvatarRequestToJSON(requestParameters['updateEquosAvatarRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosAvatarFromJSON(jsonValue));
    }

    /**
     * Update an Equos Avatar.
     * @deprecated
     */
    async avatarControllerUpdateV3(requestParameters: AvatarControllerUpdateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosAvatar> {
        const response = await this.avatarControllerUpdateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
