/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosBrainRequest,
  EquosBrain,
  ListEquosBrainsResponse,
} from '../models/index';
import {
    CreateEquosBrainRequestFromJSON,
    CreateEquosBrainRequestToJSON,
    EquosBrainFromJSON,
    EquosBrainToJSON,
    ListEquosBrainsResponseFromJSON,
    ListEquosBrainsResponseToJSON,
} from '../models/index';

export interface CreateBrainRequest {
    createEquosBrainRequest: CreateEquosBrainRequest;
}

export interface DeleteBrainRequest {
    id: string;
}

export interface GetBrainRequest {
    id: string;
}

export interface ListBrainsRequest {
    take?: number;
    skip?: number;
    client?: string;
}

/**
 * 
 */
export class BrainApi extends runtime.BaseAPI {

    /**
     * Create a new Equos Brain.
     */
    async createBrainRaw(requestParameters: CreateBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosBrain>> {
        if (requestParameters['createEquosBrainRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosBrainRequest',
                'Required parameter "createEquosBrainRequest" was null or undefined when calling createBrain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/brains`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosBrainRequestToJSON(requestParameters['createEquosBrainRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosBrainFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Brain.
     */
    async createBrain(requestParameters: CreateBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosBrain> {
        const response = await this.createBrainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an Equos Brain. This action is irreversible.
     */
    async deleteBrainRaw(requestParameters: DeleteBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosBrain>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBrain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/brains/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosBrainFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Brain. This action is irreversible.
     */
    async deleteBrain(requestParameters: DeleteBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosBrain> {
        const response = await this.deleteBrainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Brain by ID.
     */
    async getBrainRaw(requestParameters: GetBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosBrain>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBrain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/brains/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosBrainFromJSON(jsonValue));
    }

    /**
     * Get Equos Brain by ID.
     */
    async getBrain(requestParameters: GetBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosBrain> {
        const response = await this.getBrainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Brains.
     */
    async listBrainsRaw(requestParameters: ListBrainsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosBrainsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/brains`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosBrainsResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Brains.
     */
    async listBrains(requestParameters: ListBrainsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosBrainsResponse> {
        const response = await this.listBrainsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
