/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosCharacterRequest,
  EquosCharacter,
  ListEquosCharactersResponse,
  UpdateEquosCharacterRequest,
} from '../models/index';
import {
    CreateEquosCharacterRequestFromJSON,
    CreateEquosCharacterRequestToJSON,
    EquosCharacterFromJSON,
    EquosCharacterToJSON,
    ListEquosCharactersResponseFromJSON,
    ListEquosCharactersResponseToJSON,
    UpdateEquosCharacterRequestFromJSON,
    UpdateEquosCharacterRequestToJSON,
} from '../models/index';

export interface CharacterControllerCreateV3Request {
    createEquosCharacterRequest: CreateEquosCharacterRequest;
}

export interface CharacterControllerGetByIdV3Request {
    id: string;
}

export interface CharacterControllerListV3Request {
    take?: number;
    skip?: number;
    client?: string;
}

export interface CharacterControllerSoftDeleteV3Request {
    id: string;
}

export interface CharacterControllerUpdateV3Request {
    id: string;
    updateEquosCharacterRequest: UpdateEquosCharacterRequest;
}

/**
 * 
 */
export class CharacterApi extends runtime.BaseAPI {

    /**
     * Create a new Equos Character.
     */
    async characterControllerCreateV3Raw(requestParameters: CharacterControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['createEquosCharacterRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosCharacterRequest',
                'Required parameter "createEquosCharacterRequest" was null or undefined when calling characterControllerCreateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosCharacterRequestToJSON(requestParameters['createEquosCharacterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Character.
     */
    async characterControllerCreateV3(requestParameters: CharacterControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.characterControllerCreateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Character by ID.
     */
    async characterControllerGetByIdV3Raw(requestParameters: CharacterControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling characterControllerGetByIdV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Get Equos Character by ID.
     */
    async characterControllerGetByIdV3(requestParameters: CharacterControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.characterControllerGetByIdV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Characters.
     */
    async characterControllerListV3Raw(requestParameters: CharacterControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosCharactersResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosCharactersResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Characters.
     */
    async characterControllerListV3(requestParameters: CharacterControllerListV3Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosCharactersResponse> {
        const response = await this.characterControllerListV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an Equos Character. This action is irreversible.
     */
    async characterControllerSoftDeleteV3Raw(requestParameters: CharacterControllerSoftDeleteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling characterControllerSoftDeleteV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Character. This action is irreversible.
     */
    async characterControllerSoftDeleteV3(requestParameters: CharacterControllerSoftDeleteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.characterControllerSoftDeleteV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update character properties.
     */
    async characterControllerUpdateV3Raw(requestParameters: CharacterControllerUpdateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling characterControllerUpdateV3().'
            );
        }

        if (requestParameters['updateEquosCharacterRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEquosCharacterRequest',
                'Required parameter "updateEquosCharacterRequest" was null or undefined when calling characterControllerUpdateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEquosCharacterRequestToJSON(requestParameters['updateEquosCharacterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Update character properties.
     */
    async characterControllerUpdateV3(requestParameters: CharacterControllerUpdateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.characterControllerUpdateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
