/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosCharacterRequest,
  EquosCharacter,
  ListEquosCharactersResponse,
  UpdateEquosCharacterRequest,
} from '../models/index';
import {
    CreateEquosCharacterRequestFromJSON,
    CreateEquosCharacterRequestToJSON,
    EquosCharacterFromJSON,
    EquosCharacterToJSON,
    ListEquosCharactersResponseFromJSON,
    ListEquosCharactersResponseToJSON,
    UpdateEquosCharacterRequestFromJSON,
    UpdateEquosCharacterRequestToJSON,
} from '../models/index';

export interface CreateCharacterRequest {
    createEquosCharacterRequest: CreateEquosCharacterRequest;
}

export interface DeleteCharacterRequest {
    id: string;
}

export interface GetCharacterRequest {
    id: string;
}

export interface ListCharactersRequest {
    take?: number;
    skip?: number;
    client?: string;
}

export interface UpdateCharacterRequest {
    id: string;
    updateEquosCharacterRequest: UpdateEquosCharacterRequest;
}

/**
 * 
 */
export class CharacterApi extends runtime.BaseAPI {

    /**
     * Create a new Equos Character.
     */
    async createCharacterRaw(requestParameters: CreateCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['createEquosCharacterRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosCharacterRequest',
                'Required parameter "createEquosCharacterRequest" was null or undefined when calling createCharacter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosCharacterRequestToJSON(requestParameters['createEquosCharacterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Character.
     */
    async createCharacter(requestParameters: CreateCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.createCharacterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an Equos Character. This action is irreversible.
     */
    async deleteCharacterRaw(requestParameters: DeleteCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCharacter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Character. This action is irreversible.
     */
    async deleteCharacter(requestParameters: DeleteCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.deleteCharacterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Character by ID.
     */
    async getCharacterRaw(requestParameters: GetCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCharacter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Get Equos Character by ID.
     */
    async getCharacter(requestParameters: GetCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.getCharacterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Characters.
     */
    async listCharactersRaw(requestParameters: ListCharactersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosCharactersResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosCharactersResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Characters.
     */
    async listCharacters(requestParameters: ListCharactersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosCharactersResponse> {
        const response = await this.listCharactersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update character properties.
     */
    async updateCharacterRaw(requestParameters: UpdateCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosCharacter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCharacter().'
            );
        }

        if (requestParameters['updateEquosCharacterRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEquosCharacterRequest',
                'Required parameter "updateEquosCharacterRequest" was null or undefined when calling updateCharacter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/characters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEquosCharacterRequestToJSON(requestParameters['updateEquosCharacterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosCharacterFromJSON(jsonValue));
    }

    /**
     * Update character properties.
     */
    async updateCharacter(requestParameters: UpdateCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosCharacter> {
        const response = await this.updateCharacterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
