/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosConversationRequest,
  CreateEquosConversationResponse,
  EquosConversation,
  ListEquosConversationsResponse,
} from '../models/index';
import {
    CreateEquosConversationRequestFromJSON,
    CreateEquosConversationRequestToJSON,
    CreateEquosConversationResponseFromJSON,
    CreateEquosConversationResponseToJSON,
    EquosConversationFromJSON,
    EquosConversationToJSON,
    ListEquosConversationsResponseFromJSON,
    ListEquosConversationsResponseToJSON,
} from '../models/index';

export interface GetConversationByIdRequest {
    id: string;
}

export interface ListConversationsRequest {
    take?: number;
    skip?: number;
    client?: string;
}

export interface StartConversationRequest {
    createEquosConversationRequest: CreateEquosConversationRequest;
}

export interface StopConversationRequest {
    id: string;
}

/**
 * 
 */
export class ConversationApi extends runtime.BaseAPI {

    /**
     * Get Equos conversation by id.
     */
    async getConversationByIdRaw(requestParameters: GetConversationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosConversation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConversationById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/conversations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosConversationFromJSON(jsonValue));
    }

    /**
     * Get Equos conversation by id.
     */
    async getConversationById(requestParameters: GetConversationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosConversation> {
        const response = await this.getConversationByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos conversations.
     */
    async listConversationsRaw(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosConversationsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/conversations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosConversationsResponseFromJSON(jsonValue));
    }

    /**
     * List Equos conversations.
     */
    async listConversations(requestParameters: ListConversationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosConversationsResponse> {
        const response = await this.listConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start an Equos avatar sesssion.
     */
    async startConversationRaw(requestParameters: StartConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEquosConversationResponse>> {
        if (requestParameters['createEquosConversationRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosConversationRequest',
                'Required parameter "createEquosConversationRequest" was null or undefined when calling startConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/conversations`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosConversationRequestToJSON(requestParameters['createEquosConversationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEquosConversationResponseFromJSON(jsonValue));
    }

    /**
     * Start an Equos avatar sesssion.
     */
    async startConversation(requestParameters: StartConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEquosConversationResponse> {
        const response = await this.startConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop a conversation. Returns null if already stopped or conversation was not found.
     */
    async stopConversationRaw(requestParameters: StopConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosConversation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stopConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/conversations/{id}/stop`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosConversationFromJSON(jsonValue));
    }

    /**
     * Stop a conversation. Returns null if already stopped or conversation was not found.
     */
    async stopConversation(requestParameters: StopConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosConversation> {
        const response = await this.stopConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
