/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosFaceRequest,
  EquosFace,
  ListEquosFacesResponse,
} from '../models/index';
import {
    CreateEquosFaceRequestFromJSON,
    CreateEquosFaceRequestToJSON,
    EquosFaceFromJSON,
    EquosFaceToJSON,
    ListEquosFacesResponseFromJSON,
    ListEquosFacesResponseToJSON,
} from '../models/index';

export interface CreateFaceRequest {
    createEquosFaceRequest: CreateEquosFaceRequest;
}

export interface DeleteFaceRequest {
    id: string;
}

export interface GetFaceRequest {
    id: string;
}

export interface ListFacesRequest {
    take?: number;
    skip?: number;
    client?: string;
}

/**
 * 
 */
export class FaceApi extends runtime.BaseAPI {

    /**
     * Create a new Equos Face.
     */
    async createFaceRaw(requestParameters: CreateFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosFace>> {
        if (requestParameters['createEquosFaceRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosFaceRequest',
                'Required parameter "createEquosFaceRequest" was null or undefined when calling createFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/faces`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosFaceRequestToJSON(requestParameters['createEquosFaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosFaceFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Face.
     */
    async createFace(requestParameters: CreateFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosFace> {
        const response = await this.createFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an Equos Face. This action is irreversible.
     */
    async deleteFaceRaw(requestParameters: DeleteFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosFace>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/faces/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosFaceFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Face. This action is irreversible.
     */
    async deleteFace(requestParameters: DeleteFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosFace> {
        const response = await this.deleteFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Face by ID.
     */
    async getFaceRaw(requestParameters: GetFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosFace>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/faces/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosFaceFromJSON(jsonValue));
    }

    /**
     * Get Equos Face by ID.
     */
    async getFace(requestParameters: GetFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosFace> {
        const response = await this.getFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Faces.
     */
    async listFacesRaw(requestParameters: ListFacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosFacesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/faces`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosFacesResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Faces.
     */
    async listFaces(requestParameters: ListFacesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosFacesResponse> {
        const response = await this.listFacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
