/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface KnowledgeBaseControllerAddDocumentV3Request {
    id: string;
    body: object;
}

export interface KnowledgeBaseControllerCreateKnowledgeBaseV3Request {
    body: object;
}

export interface KnowledgeBaseControllerDeleteDocV3Request {
    id: string;
    doc: string;
}

export interface KnowledgeBaseControllerDeleteV3Request {
    id: string;
}

export interface KnowledgeBaseControllerGetByIdV3Request {
    id: string;
}

export interface KnowledgeBaseControllerIndexDocumentV3Request {
    id: string;
    doc: string;
}

export interface KnowledgeBaseControllerListV3Request {
    take: string;
    skip: string;
}

/**
 * 
 */
export class KnowledgeBaseApi extends runtime.BaseAPI {

    /**
     */
    async knowledgeBaseControllerAddDocumentV3Raw(requestParameters: KnowledgeBaseControllerAddDocumentV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeBaseControllerAddDocumentV3().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling knowledgeBaseControllerAddDocumentV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}/documents`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerAddDocumentV3(requestParameters: KnowledgeBaseControllerAddDocumentV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerAddDocumentV3Raw(requestParameters, initOverrides);
    }

    /**
     */
    async knowledgeBaseControllerCreateKnowledgeBaseV3Raw(requestParameters: KnowledgeBaseControllerCreateKnowledgeBaseV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling knowledgeBaseControllerCreateKnowledgeBaseV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerCreateKnowledgeBaseV3(requestParameters: KnowledgeBaseControllerCreateKnowledgeBaseV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerCreateKnowledgeBaseV3Raw(requestParameters, initOverrides);
    }

    /**
     */
    async knowledgeBaseControllerDeleteDocV3Raw(requestParameters: KnowledgeBaseControllerDeleteDocV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeBaseControllerDeleteDocV3().'
            );
        }

        if (requestParameters['doc'] == null) {
            throw new runtime.RequiredError(
                'doc',
                'Required parameter "doc" was null or undefined when calling knowledgeBaseControllerDeleteDocV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}/documents/{doc}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"doc"}}`, encodeURIComponent(String(requestParameters['doc'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerDeleteDocV3(requestParameters: KnowledgeBaseControllerDeleteDocV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerDeleteDocV3Raw(requestParameters, initOverrides);
    }

    /**
     */
    async knowledgeBaseControllerDeleteV3Raw(requestParameters: KnowledgeBaseControllerDeleteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeBaseControllerDeleteV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerDeleteV3(requestParameters: KnowledgeBaseControllerDeleteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerDeleteV3Raw(requestParameters, initOverrides);
    }

    /**
     */
    async knowledgeBaseControllerGetByIdV3Raw(requestParameters: KnowledgeBaseControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeBaseControllerGetByIdV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerGetByIdV3(requestParameters: KnowledgeBaseControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerGetByIdV3Raw(requestParameters, initOverrides);
    }

    /**
     */
    async knowledgeBaseControllerIndexDocumentV3Raw(requestParameters: KnowledgeBaseControllerIndexDocumentV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeBaseControllerIndexDocumentV3().'
            );
        }

        if (requestParameters['doc'] == null) {
            throw new runtime.RequiredError(
                'doc',
                'Required parameter "doc" was null or undefined when calling knowledgeBaseControllerIndexDocumentV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}/documents/{doc}/index`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"doc"}}`, encodeURIComponent(String(requestParameters['doc'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerIndexDocumentV3(requestParameters: KnowledgeBaseControllerIndexDocumentV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerIndexDocumentV3Raw(requestParameters, initOverrides);
    }

    /**
     */
    async knowledgeBaseControllerListV3Raw(requestParameters: KnowledgeBaseControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['take'] == null) {
            throw new runtime.RequiredError(
                'take',
                'Required parameter "take" was null or undefined when calling knowledgeBaseControllerListV3().'
            );
        }

        if (requestParameters['skip'] == null) {
            throw new runtime.RequiredError(
                'skip',
                'Required parameter "skip" was null or undefined when calling knowledgeBaseControllerListV3().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async knowledgeBaseControllerListV3(requestParameters: KnowledgeBaseControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeBaseControllerListV3Raw(requestParameters, initOverrides);
    }

}
