/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDocumentRequest,
  CreateDocumentResponse,
  CreateKnowledgeBaseRequest,
  EquosDocument,
  EquosKnowledgeBase,
  ListEquosKnowledgeBasesResponse,
} from '../models/index';
import {
    CreateDocumentRequestFromJSON,
    CreateDocumentRequestToJSON,
    CreateDocumentResponseFromJSON,
    CreateDocumentResponseToJSON,
    CreateKnowledgeBaseRequestFromJSON,
    CreateKnowledgeBaseRequestToJSON,
    EquosDocumentFromJSON,
    EquosDocumentToJSON,
    EquosKnowledgeBaseFromJSON,
    EquosKnowledgeBaseToJSON,
    ListEquosKnowledgeBasesResponseFromJSON,
    ListEquosKnowledgeBasesResponseToJSON,
} from '../models/index';

export interface AddDocumentRequest {
    id: string;
    createDocumentRequest: CreateDocumentRequest;
}

export interface CreateKnowledgeBaseOperationRequest {
    createKnowledgeBaseRequest: CreateKnowledgeBaseRequest;
}

export interface DeleteDocumentRequest {
    id: string;
    doc: string;
}

export interface DeleteKnowledgeBaseRequest {
    id: string;
}

export interface GetKnowledgeBaseRequest {
    id: string;
}

export interface IndexDocumentRequest {
    id: string;
    doc: string;
}

export interface ListKnowledgeBasesRequest {
    take?: number;
    skip?: number;
    client?: string;
}

/**
 * 
 */
export class KnowledgeBaseApi extends runtime.BaseAPI {

    /**
     * Add a document to a Knowledge Base.
     */
    async addDocumentRaw(requestParameters: AddDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDocumentResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addDocument().'
            );
        }

        if (requestParameters['createDocumentRequest'] == null) {
            throw new runtime.RequiredError(
                'createDocumentRequest',
                'Required parameter "createDocumentRequest" was null or undefined when calling addDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}/documents`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDocumentRequestToJSON(requestParameters['createDocumentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDocumentResponseFromJSON(jsonValue));
    }

    /**
     * Add a document to a Knowledge Base.
     */
    async addDocument(requestParameters: AddDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDocumentResponse> {
        const response = await this.addDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Knowledge Base.
     */
    async createKnowledgeBaseRaw(requestParameters: CreateKnowledgeBaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosKnowledgeBase>> {
        if (requestParameters['createKnowledgeBaseRequest'] == null) {
            throw new runtime.RequiredError(
                'createKnowledgeBaseRequest',
                'Required parameter "createKnowledgeBaseRequest" was null or undefined when calling createKnowledgeBase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateKnowledgeBaseRequestToJSON(requestParameters['createKnowledgeBaseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosKnowledgeBaseFromJSON(jsonValue));
    }

    /**
     * Create a new Knowledge Base.
     */
    async createKnowledgeBase(requestParameters: CreateKnowledgeBaseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosKnowledgeBase> {
        const response = await this.createKnowledgeBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a document from a Knowledge Base.
     */
    async deleteDocumentRaw(requestParameters: DeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosDocument>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDocument().'
            );
        }

        if (requestParameters['doc'] == null) {
            throw new runtime.RequiredError(
                'doc',
                'Required parameter "doc" was null or undefined when calling deleteDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}/documents/{doc}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"doc"}}`, encodeURIComponent(String(requestParameters['doc'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosDocumentFromJSON(jsonValue));
    }

    /**
     * Delete a document from a Knowledge Base.
     */
    async deleteDocument(requestParameters: DeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosDocument> {
        const response = await this.deleteDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a Knowledge Base. This action is irreversible.
     */
    async deleteKnowledgeBaseRaw(requestParameters: DeleteKnowledgeBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosKnowledgeBase>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteKnowledgeBase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosKnowledgeBaseFromJSON(jsonValue));
    }

    /**
     * Delete a Knowledge Base. This action is irreversible.
     */
    async deleteKnowledgeBase(requestParameters: DeleteKnowledgeBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosKnowledgeBase> {
        const response = await this.deleteKnowledgeBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Knowledge Base by ID.
     */
    async getKnowledgeBaseRaw(requestParameters: GetKnowledgeBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosKnowledgeBase>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getKnowledgeBase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosKnowledgeBaseFromJSON(jsonValue));
    }

    /**
     * Get Knowledge Base by ID.
     */
    async getKnowledgeBase(requestParameters: GetKnowledgeBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosKnowledgeBase> {
        const response = await this.getKnowledgeBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index a document in a Knowledge Base.
     */
    async indexDocumentRaw(requestParameters: IndexDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosDocument>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling indexDocument().'
            );
        }

        if (requestParameters['doc'] == null) {
            throw new runtime.RequiredError(
                'doc',
                'Required parameter "doc" was null or undefined when calling indexDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases/{id}/documents/{doc}/index`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"doc"}}`, encodeURIComponent(String(requestParameters['doc'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosDocumentFromJSON(jsonValue));
    }

    /**
     * Index a document in a Knowledge Base.
     */
    async indexDocument(requestParameters: IndexDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosDocument> {
        const response = await this.indexDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Knowledge Bases.
     */
    async listKnowledgeBasesRaw(requestParameters: ListKnowledgeBasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosKnowledgeBasesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/knowledge-bases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosKnowledgeBasesResponseFromJSON(jsonValue));
    }

    /**
     * List Knowledge Bases.
     */
    async listKnowledgeBases(requestParameters: ListKnowledgeBasesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosKnowledgeBasesResponse> {
        const response = await this.listKnowledgeBasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
