/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EquosLimitResponse,
} from '../models/index';
import {
    EquosLimitResponseFromJSON,
    EquosLimitResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class LimitsApi extends runtime.BaseAPI {

    /**
     * Get organization limits.
     */
    async getLimitRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosLimitResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/limits`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosLimitResponseFromJSON(jsonValue));
    }

    /**
     * Get organization limits.
     */
    async getLimit(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosLimitResponse> {
        const response = await this.getLimitRaw(initOverrides);
        return await response.value();
    }

}
