/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosSessionResponse,
  CreateSessionPassRequest,
  EquosSession,
} from '../models/index';
import {
    CreateEquosSessionResponseFromJSON,
    CreateEquosSessionResponseToJSON,
    CreateSessionPassRequestFromJSON,
    CreateSessionPassRequestToJSON,
    EquosSessionFromJSON,
    EquosSessionToJSON,
} from '../models/index';

export interface SessionPassesControllerStartV3Request {
    createSessionPassRequest: CreateSessionPassRequest;
}

export interface SessionPassesControllerStopV3Request {
    id: string;
}

/**
 * 
 */
export class SessionPassesApi extends runtime.BaseAPI {

    /**
     * Start an Equos avatar sesssion.
     * @deprecated
     */
    async sessionPassesControllerStartV3Raw(requestParameters: SessionPassesControllerStartV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEquosSessionResponse>> {
        if (requestParameters['createSessionPassRequest'] == null) {
            throw new runtime.RequiredError(
                'createSessionPassRequest',
                'Required parameter "createSessionPassRequest" was null or undefined when calling sessionPassesControllerStartV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("clientAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v3/session-passes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionPassRequestToJSON(requestParameters['createSessionPassRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEquosSessionResponseFromJSON(jsonValue));
    }

    /**
     * Start an Equos avatar sesssion.
     * @deprecated
     */
    async sessionPassesControllerStartV3(requestParameters: SessionPassesControllerStartV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEquosSessionResponse> {
        const response = await this.sessionPassesControllerStartV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * End an equos session. Returns null if already stopped or session was not found.
     * @deprecated
     */
    async sessionPassesControllerStopV3Raw(requestParameters: SessionPassesControllerStopV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosSession>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessionPassesControllerStopV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("clientAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v3/session-passes/{id}/stop`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosSessionFromJSON(jsonValue));
    }

    /**
     * End an equos session. Returns null if already stopped or session was not found.
     * @deprecated
     */
    async sessionPassesControllerStopV3(requestParameters: SessionPassesControllerStopV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosSession> {
        const response = await this.sessionPassesControllerStopV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
