/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosSessionRequest,
  CreateEquosSessionResponse,
  EquosSession,
  ListEquosSessionsResponse,
} from '../models/index';
import {
    CreateEquosSessionRequestFromJSON,
    CreateEquosSessionRequestToJSON,
    CreateEquosSessionResponseFromJSON,
    CreateEquosSessionResponseToJSON,
    EquosSessionFromJSON,
    EquosSessionToJSON,
    ListEquosSessionsResponseFromJSON,
    ListEquosSessionsResponseToJSON,
} from '../models/index';

export interface SessionsControllerCreateV3Request {
    createEquosSessionRequest: CreateEquosSessionRequest;
}

export interface SessionsControllerGetByIdV3Request {
    id: string;
}

export interface SessionsControllerListV3Request {
    take?: number;
    skip?: number;
    client?: string;
}

export interface SessionsControllerStopV3Request {
    id: string;
}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI {

    /**
     * Start an Equos avatar sesssion.
     * @deprecated
     */
    async sessionsControllerCreateV3Raw(requestParameters: SessionsControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEquosSessionResponse>> {
        if (requestParameters['createEquosSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosSessionRequest',
                'Required parameter "createEquosSessionRequest" was null or undefined when calling sessionsControllerCreateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosSessionRequestToJSON(requestParameters['createEquosSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEquosSessionResponseFromJSON(jsonValue));
    }

    /**
     * Start an Equos avatar sesssion.
     * @deprecated
     */
    async sessionsControllerCreateV3(requestParameters: SessionsControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEquosSessionResponse> {
        const response = await this.sessionsControllerCreateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Session by ID.
     * @deprecated
     */
    async sessionsControllerGetByIdV3Raw(requestParameters: SessionsControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosSession>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessionsControllerGetByIdV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/sessions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosSessionFromJSON(jsonValue));
    }

    /**
     * Get Equos Session by ID.
     * @deprecated
     */
    async sessionsControllerGetByIdV3(requestParameters: SessionsControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosSession> {
        const response = await this.sessionsControllerGetByIdV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Sessions.
     * @deprecated
     */
    async sessionsControllerListV3Raw(requestParameters: SessionsControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosSessionsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosSessionsResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Sessions.
     * @deprecated
     */
    async sessionsControllerListV3(requestParameters: SessionsControllerListV3Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosSessionsResponse> {
        const response = await this.sessionsControllerListV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * End an equos session. Returns null if already stopped or session was not found.
     * @deprecated
     */
    async sessionsControllerStopV3Raw(requestParameters: SessionsControllerStopV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosSession>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessionsControllerStopV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/sessions/{id}/stop`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosSessionFromJSON(jsonValue));
    }

    /**
     * End an equos session. Returns null if already stopped or session was not found.
     * @deprecated
     */
    async sessionsControllerStopV3(requestParameters: SessionsControllerStopV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosSession> {
        const response = await this.sessionsControllerStopV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
