/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquosVoiceRequest,
  EquosVoice,
  ListEquosVoicesResponse,
} from '../models/index';
import {
    CreateEquosVoiceRequestFromJSON,
    CreateEquosVoiceRequestToJSON,
    EquosVoiceFromJSON,
    EquosVoiceToJSON,
    ListEquosVoicesResponseFromJSON,
    ListEquosVoicesResponseToJSON,
} from '../models/index';

export interface VoiceControllerCreateV3Request {
    createEquosVoiceRequest: CreateEquosVoiceRequest;
}

export interface VoiceControllerGetByIdV3Request {
    id: string;
}

export interface VoiceControllerListV3Request {
    take?: number;
    skip?: number;
    client?: string;
}

export interface VoiceControllerSoftDeleteV3Request {
    id: string;
}

/**
 * 
 */
export class VoiceApi extends runtime.BaseAPI {

    /**
     * Create a new Equos Voice.
     */
    async voiceControllerCreateV3Raw(requestParameters: VoiceControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosVoice>> {
        if (requestParameters['createEquosVoiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createEquosVoiceRequest',
                'Required parameter "createEquosVoiceRequest" was null or undefined when calling voiceControllerCreateV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/voices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquosVoiceRequestToJSON(requestParameters['createEquosVoiceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosVoiceFromJSON(jsonValue));
    }

    /**
     * Create a new Equos Voice.
     */
    async voiceControllerCreateV3(requestParameters: VoiceControllerCreateV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosVoice> {
        const response = await this.voiceControllerCreateV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Equos Voice by ID.
     */
    async voiceControllerGetByIdV3Raw(requestParameters: VoiceControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosVoice>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling voiceControllerGetByIdV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/voices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosVoiceFromJSON(jsonValue));
    }

    /**
     * Get Equos Voice by ID.
     */
    async voiceControllerGetByIdV3(requestParameters: VoiceControllerGetByIdV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosVoice> {
        const response = await this.voiceControllerGetByIdV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Equos Voices.
     */
    async voiceControllerListV3Raw(requestParameters: VoiceControllerListV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEquosVoicesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['client'] != null) {
            queryParameters['client'] = requestParameters['client'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/voices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEquosVoicesResponseFromJSON(jsonValue));
    }

    /**
     * List Equos Voices.
     */
    async voiceControllerListV3(requestParameters: VoiceControllerListV3Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEquosVoicesResponse> {
        const response = await this.voiceControllerListV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an Equos Voice. This action is irreversible.
     */
    async voiceControllerSoftDeleteV3Raw(requestParameters: VoiceControllerSoftDeleteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquosVoice>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling voiceControllerSoftDeleteV3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }


        let urlPath = `/v3/voices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquosVoiceFromJSON(jsonValue));
    }

    /**
     * Delete an Equos Voice. This action is irreversible.
     */
    async voiceControllerSoftDeleteV3(requestParameters: VoiceControllerSoftDeleteV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquosVoice> {
        const response = await this.voiceControllerSoftDeleteV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
