/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosVoiceRequest
 */
export interface CreateEquosVoiceRequest {
    /**
     * Client identifier associated with the voice. This is useful to segment resources by client.
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    identity: CreateEquosVoiceRequestIdentityEnum;
    /**
     * Instructions for the voice such as tone, rythm, etc.
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    instructions?: string | null;
}


/**
 * @export
 */
export const CreateEquosVoiceRequestIdentityEnum = {
    Puck: 'Puck',
    Charon: 'Charon',
    Kore: 'Kore',
    Fenrir: 'Fenrir',
    Aoede: 'Aoede',
    Leda: 'Leda',
    Orus: 'Orus',
    Zephyr: 'Zephyr',
    Sulafat: 'Sulafat',
    Sadachbia: 'Sadachbia',
    Sadaltager: 'Sadaltager',
    Vindemiatrix: 'Vindemiatrix',
    Zubenelgenubi: 'Zubenelgenubi',
    Achird: 'Achird',
    Pulcherrima: 'Pulcherrima',
    Gacrux: 'Gacrux',
    Schedar: 'Schedar',
    Alnilam: 'Alnilam',
    Achernar: 'Achernar',
    Laomedeia: 'Laomedeia',
    Rasalgethi: 'Rasalgethi',
    Algenib: 'Algenib',
    Erinome: 'Erinome',
    Despina: 'Despina',
    Algieba: 'Algieba',
    Umbriel: 'Umbriel',
    Iapetus: 'Iapetus',
    Enceladus: 'Enceladus',
    Autonoe: 'Autonoe',
    Callirrhoe: 'Callirrhoe'
} as const;
export type CreateEquosVoiceRequestIdentityEnum = typeof CreateEquosVoiceRequestIdentityEnum[keyof typeof CreateEquosVoiceRequestIdentityEnum];


/**
 * Check if a given object implements the CreateEquosVoiceRequest interface.
 */
export function instanceOfCreateEquosVoiceRequest(value: object): value is CreateEquosVoiceRequest {
    if (!('identity' in value) || value['identity'] === undefined) return false;
    return true;
}

export function CreateEquosVoiceRequestFromJSON(json: any): CreateEquosVoiceRequest {
    return CreateEquosVoiceRequestFromJSONTyped(json, false);
}

export function CreateEquosVoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosVoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'] == null ? undefined : json['client'],
        'identity': json['identity'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
    };
}

export function CreateEquosVoiceRequestToJSON(json: any): CreateEquosVoiceRequest {
    return CreateEquosVoiceRequestToJSONTyped(json, false);
}

export function CreateEquosVoiceRequestToJSONTyped(value?: CreateEquosVoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
        'identity': value['identity'],
        'instructions': value['instructions'],
    };
}

