/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosSession } from './EquosSession';
import {
    EquosSessionFromJSON,
    EquosSessionFromJSONTyped,
    EquosSessionToJSON,
    EquosSessionToJSONTyped,
} from './EquosSession';

/**
 * 
 * @export
 * @interface CreateEquosSessionResponse
 */
export interface CreateEquosSessionResponse {
    /**
     * 
     * @type {EquosSession}
     * @memberof CreateEquosSessionResponse
     */
    session: EquosSession;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosSessionResponse
     */
    consumerAccessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosSessionResponse
     */
    remoteAgentAccessToken?: string;
}

/**
 * Check if a given object implements the CreateEquosSessionResponse interface.
 */
export function instanceOfCreateEquosSessionResponse(value: object): value is CreateEquosSessionResponse {
    if (!('session' in value) || value['session'] === undefined) return false;
    return true;
}

export function CreateEquosSessionResponseFromJSON(json: any): CreateEquosSessionResponse {
    return CreateEquosSessionResponseFromJSONTyped(json, false);
}

export function CreateEquosSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'session': EquosSessionFromJSON(json['session']),
        'consumerAccessToken': json['consumerAccessToken'] == null ? undefined : json['consumerAccessToken'],
        'remoteAgentAccessToken': json['remoteAgentAccessToken'] == null ? undefined : json['remoteAgentAccessToken'],
    };
}

export function CreateEquosSessionResponseToJSON(json: any): CreateEquosSessionResponse {
    return CreateEquosSessionResponseToJSONTyped(json, false);
}

export function CreateEquosSessionResponseToJSONTyped(value?: CreateEquosSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session': EquosSessionToJSON(value['session']),
        'consumerAccessToken': value['consumerAccessToken'],
        'remoteAgentAccessToken': value['remoteAgentAccessToken'],
    };
}

