/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateKnowledgeBaseRequest
 */
export interface CreateKnowledgeBaseRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeBaseRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeBaseRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKnowledgeBaseRequest
     */
    client?: string;
}

/**
 * Check if a given object implements the CreateKnowledgeBaseRequest interface.
 */
export function instanceOfCreateKnowledgeBaseRequest(value: object): value is CreateKnowledgeBaseRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateKnowledgeBaseRequestFromJSON(json: any): CreateKnowledgeBaseRequest {
    return CreateKnowledgeBaseRequestFromJSONTyped(json, false);
}

export function CreateKnowledgeBaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKnowledgeBaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'client': json['client'] == null ? undefined : json['client'],
    };
}

export function CreateKnowledgeBaseRequestToJSON(json: any): CreateKnowledgeBaseRequest {
    return CreateKnowledgeBaseRequestToJSONTyped(json, false);
}

export function CreateKnowledgeBaseRequestToJSONTyped(value?: CreateKnowledgeBaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'client': value['client'],
    };
}

