/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosDocument } from './EquosDocument';
import {
    EquosDocumentFromJSON,
    EquosDocumentFromJSONTyped,
    EquosDocumentToJSON,
    EquosDocumentToJSONTyped,
} from './EquosDocument';

/**
 * 
 * @export
 * @interface CreateDocumentResponse
 */
export interface CreateDocumentResponse {
    /**
     * 
     * @type {EquosDocument}
     * @memberof CreateDocumentResponse
     */
    document: EquosDocument;
}

/**
 * Check if a given object implements the CreateDocumentResponse interface.
 */
export function instanceOfCreateDocumentResponse(value: object): value is CreateDocumentResponse {
    if (!('document' in value) || value['document'] === undefined) return false;
    return true;
}

export function CreateDocumentResponseFromJSON(json: any): CreateDocumentResponse {
    return CreateDocumentResponseFromJSONTyped(json, false);
}

export function CreateDocumentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDocumentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'document': EquosDocumentFromJSON(json['document']),
    };
}

export function CreateDocumentResponseToJSON(json: any): CreateDocumentResponse {
    return CreateDocumentResponseToJSONTyped(json, false);
}

export function CreateDocumentResponseToJSONTyped(value?: CreateDocumentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document': EquosDocumentToJSON(value['document']),
    };
}

