/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosVoiceRequest
 */
export interface CreateEquosVoiceRequest {
    /**
     * Client identifier associated with the voice. This is useful to segment resources by client.
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    sampleUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosVoiceRequest
     */
    voiceId: string;
}

/**
 * Check if a given object implements the CreateEquosVoiceRequest interface.
 */
export function instanceOfCreateEquosVoiceRequest(value: object): value is CreateEquosVoiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('sampleUrl' in value) || value['sampleUrl'] === undefined) return false;
    if (!('voiceId' in value) || value['voiceId'] === undefined) return false;
    return true;
}

export function CreateEquosVoiceRequestFromJSON(json: any): CreateEquosVoiceRequest {
    return CreateEquosVoiceRequestFromJSONTyped(json, false);
}

export function CreateEquosVoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosVoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'] == null ? undefined : json['client'],
        'name': json['name'],
        'description': json['description'],
        'sampleUrl': json['sampleUrl'],
        'voiceId': json['voiceId'],
    };
}

export function CreateEquosVoiceRequestToJSON(json: any): CreateEquosVoiceRequest {
    return CreateEquosVoiceRequestToJSONTyped(json, false);
}

export function CreateEquosVoiceRequestToJSONTyped(value?: CreateEquosVoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
        'name': value['name'],
        'description': value['description'],
        'sampleUrl': value['sampleUrl'],
        'voiceId': value['voiceId'],
    };
}

