/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosSessionHost } from './EquosSessionHost';
import {
    EquosSessionHostFromJSON,
    EquosSessionHostFromJSONTyped,
    EquosSessionHostToJSON,
    EquosSessionHostToJSONTyped,
} from './EquosSessionHost';
import type { CreateEquosSessionRequestAvatar } from './CreateEquosSessionRequestAvatar';
import {
    CreateEquosSessionRequestAvatarFromJSON,
    CreateEquosSessionRequestAvatarFromJSONTyped,
    CreateEquosSessionRequestAvatarToJSON,
    CreateEquosSessionRequestAvatarToJSONTyped,
} from './CreateEquosSessionRequestAvatar';
import type { CreateEquosSessionRequestAgent } from './CreateEquosSessionRequestAgent';
import {
    CreateEquosSessionRequestAgentFromJSON,
    CreateEquosSessionRequestAgentFromJSONTyped,
    CreateEquosSessionRequestAgentToJSON,
    CreateEquosSessionRequestAgentToJSONTyped,
} from './CreateEquosSessionRequestAgent';
import type { EquosParticipantIdentity } from './EquosParticipantIdentity';
import {
    EquosParticipantIdentityFromJSON,
    EquosParticipantIdentityFromJSONTyped,
    EquosParticipantIdentityToJSON,
    EquosParticipantIdentityToJSONTyped,
} from './EquosParticipantIdentity';

/**
 * 
 * @export
 * @interface CreateEquosSessionRequest
 */
export interface CreateEquosSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEquosSessionRequest
     */
    name: string;
    /**
     * User-side client identifier.
     * @type {string}
     * @memberof CreateEquosSessionRequest
     */
    client?: string;
    /**
     * [Optional] Host configuration for self-hosted livekit sessions.
     * @type {EquosSessionHost}
     * @memberof CreateEquosSessionRequest
     */
    host?: EquosSessionHost;
    /**
     * [Optional] Max session duration in seconds. Must be less than organization limit.
     * @type {number}
     * @memberof CreateEquosSessionRequest
     */
    maxDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosSessionRequest
     */
    additionalCtx?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosSessionRequest
     */
    templateVars?: object;
    /**
     * 
     * @type {CreateEquosSessionRequestAgent}
     * @memberof CreateEquosSessionRequest
     */
    agent?: CreateEquosSessionRequestAgent;
    /**
     * 
     * @type {CreateEquosSessionRequestAvatar}
     * @memberof CreateEquosSessionRequest
     */
    avatar: CreateEquosSessionRequestAvatar;
    /**
     * [Optional] Identity of the agent that will forward audio to your Equos Avatar. Required for self-hosted agents.
     * @type {EquosParticipantIdentity}
     * @memberof CreateEquosSessionRequest
     */
    remoteAgentConnectingIdentity?: EquosParticipantIdentity;
    /**
     * [Optional] Identity of the end user that will interact with the agent in the session. Required if not self-hosted session.
     * @type {EquosParticipantIdentity}
     * @memberof CreateEquosSessionRequest
     */
    consumerIdentity?: EquosParticipantIdentity;
}

/**
 * Check if a given object implements the CreateEquosSessionRequest interface.
 */
export function instanceOfCreateEquosSessionRequest(value: object): value is CreateEquosSessionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function CreateEquosSessionRequestFromJSON(json: any): CreateEquosSessionRequest {
    return CreateEquosSessionRequestFromJSONTyped(json, false);
}

export function CreateEquosSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'client': json['client'] == null ? undefined : json['client'],
        'host': json['host'] == null ? undefined : EquosSessionHostFromJSON(json['host']),
        'maxDuration': json['maxDuration'] == null ? undefined : json['maxDuration'],
        'additionalCtx': json['additionalCtx'] == null ? undefined : json['additionalCtx'],
        'templateVars': json['templateVars'] == null ? undefined : json['templateVars'],
        'agent': json['agent'] == null ? undefined : CreateEquosSessionRequestAgentFromJSON(json['agent']),
        'avatar': CreateEquosSessionRequestAvatarFromJSON(json['avatar']),
        'remoteAgentConnectingIdentity': json['remoteAgentConnectingIdentity'] == null ? undefined : EquosParticipantIdentityFromJSON(json['remoteAgentConnectingIdentity']),
        'consumerIdentity': json['consumerIdentity'] == null ? undefined : EquosParticipantIdentityFromJSON(json['consumerIdentity']),
    };
}

export function CreateEquosSessionRequestToJSON(json: any): CreateEquosSessionRequest {
    return CreateEquosSessionRequestToJSONTyped(json, false);
}

export function CreateEquosSessionRequestToJSONTyped(value?: CreateEquosSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'client': value['client'],
        'host': EquosSessionHostToJSON(value['host']),
        'maxDuration': value['maxDuration'],
        'additionalCtx': value['additionalCtx'],
        'templateVars': value['templateVars'],
        'agent': CreateEquosSessionRequestAgentToJSON(value['agent']),
        'avatar': CreateEquosSessionRequestAvatarToJSON(value['avatar']),
        'remoteAgentConnectingIdentity': EquosParticipantIdentityToJSON(value['remoteAgentConnectingIdentity']),
        'consumerIdentity': EquosParticipantIdentityToJSON(value['consumerIdentity']),
    };
}

