/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosBrainRequest
 */
export interface CreateEquosBrainRequest {
    /**
     * Client identifier associated with the brain. This is useful to segment resources by client.
     * @type {string}
     * @memberof CreateEquosBrainRequest
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosBrainRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosBrainRequest
     */
    instructions: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosBrainRequest
     */
    greetingMessage: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosBrainRequest
     */
    model: string;
}

/**
 * Check if a given object implements the CreateEquosBrainRequest interface.
 */
export function instanceOfCreateEquosBrainRequest(value: object): value is CreateEquosBrainRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('greetingMessage' in value) || value['greetingMessage'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function CreateEquosBrainRequestFromJSON(json: any): CreateEquosBrainRequest {
    return CreateEquosBrainRequestFromJSONTyped(json, false);
}

export function CreateEquosBrainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosBrainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'] == null ? undefined : json['client'],
        'name': json['name'],
        'instructions': json['instructions'],
        'greetingMessage': json['greetingMessage'],
        'model': json['model'],
    };
}

export function CreateEquosBrainRequestToJSON(json: any): CreateEquosBrainRequest {
    return CreateEquosBrainRequestToJSONTyped(json, false);
}

export function CreateEquosBrainRequestToJSONTyped(value?: CreateEquosBrainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
        'name': value['name'],
        'instructions': value['instructions'],
        'greetingMessage': value['greetingMessage'],
        'model': value['model'],
    };
}

