/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosResourceReference } from './EquosResourceReference';
import {
    EquosResourceReferenceFromJSON,
    EquosResourceReferenceFromJSONTyped,
    EquosResourceReferenceToJSON,
    EquosResourceReferenceToJSONTyped,
} from './EquosResourceReference';
import type { EquosParticipantIdentity } from './EquosParticipantIdentity';
import {
    EquosParticipantIdentityFromJSON,
    EquosParticipantIdentityFromJSONTyped,
    EquosParticipantIdentityToJSON,
    EquosParticipantIdentityToJSONTyped,
} from './EquosParticipantIdentity';

/**
 * 
 * @export
 * @interface CreateSessionPassRequest
 */
export interface CreateSessionPassRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionPassRequest
     */
    name: string;
    /**
     * [Optional] User-side client identifier.
     * @type {string}
     * @memberof CreateSessionPassRequest
     */
    client?: string;
    /**
     * [Optional] Max session duration in seconds. Must be less than organization limit.
     * @type {number}
     * @memberof CreateSessionPassRequest
     */
    maxDuration?: number;
    /**
     * Existing equos avatar ID.
     * @type {EquosResourceReference}
     * @memberof CreateSessionPassRequest
     */
    avatar: EquosResourceReference;
    /**
     * Existing equos agent ID.
     * @type {EquosResourceReference}
     * @memberof CreateSessionPassRequest
     */
    agent: EquosResourceReference;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionPassRequest
     */
    additionalCtx?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateSessionPassRequest
     */
    templateVars?: object;
    /**
     * Identity of the end user that will interact with the agent in the session.
     * @type {EquosParticipantIdentity}
     * @memberof CreateSessionPassRequest
     */
    consumerIdentity: EquosParticipantIdentity;
}

/**
 * Check if a given object implements the CreateSessionPassRequest interface.
 */
export function instanceOfCreateSessionPassRequest(value: object): value is CreateSessionPassRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('consumerIdentity' in value) || value['consumerIdentity'] === undefined) return false;
    return true;
}

export function CreateSessionPassRequestFromJSON(json: any): CreateSessionPassRequest {
    return CreateSessionPassRequestFromJSONTyped(json, false);
}

export function CreateSessionPassRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionPassRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'client': json['client'] == null ? undefined : json['client'],
        'maxDuration': json['maxDuration'] == null ? undefined : json['maxDuration'],
        'avatar': EquosResourceReferenceFromJSON(json['avatar']),
        'agent': EquosResourceReferenceFromJSON(json['agent']),
        'additionalCtx': json['additionalCtx'] == null ? undefined : json['additionalCtx'],
        'templateVars': json['templateVars'] == null ? undefined : json['templateVars'],
        'consumerIdentity': EquosParticipantIdentityFromJSON(json['consumerIdentity']),
    };
}

export function CreateSessionPassRequestToJSON(json: any): CreateSessionPassRequest {
    return CreateSessionPassRequestToJSONTyped(json, false);
}

export function CreateSessionPassRequestToJSONTyped(value?: CreateSessionPassRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'client': value['client'],
        'maxDuration': value['maxDuration'],
        'avatar': EquosResourceReferenceToJSON(value['avatar']),
        'agent': EquosResourceReferenceToJSON(value['agent']),
        'additionalCtx': value['additionalCtx'],
        'templateVars': value['templateVars'],
        'consumerIdentity': EquosParticipantIdentityToJSON(value['consumerIdentity']),
    };
}

