/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateEquosAvatarRequest } from './CreateEquosAvatarRequest';
import {
    instanceOfCreateEquosAvatarRequest,
    CreateEquosAvatarRequestFromJSON,
    CreateEquosAvatarRequestFromJSONTyped,
    CreateEquosAvatarRequestToJSON,
} from './CreateEquosAvatarRequest';
import type { EquosResourceReference } from './EquosResourceReference';
import {
    instanceOfEquosResourceReference,
    EquosResourceReferenceFromJSON,
    EquosResourceReferenceFromJSONTyped,
    EquosResourceReferenceToJSON,
} from './EquosResourceReference';

/**
 * @type CreateEquosSessionRequestAvatar
 * Either provide an existing avatar ID or create a new avatar on the fly.
 * @export
 */
export type CreateEquosSessionRequestAvatar = CreateEquosAvatarRequest | EquosResourceReference;

export function CreateEquosSessionRequestAvatarFromJSON(json: any): CreateEquosSessionRequestAvatar {
    return CreateEquosSessionRequestAvatarFromJSONTyped(json, false);
}

export function CreateEquosSessionRequestAvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosSessionRequestAvatar {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCreateEquosAvatarRequest(json)) {
        return CreateEquosAvatarRequestFromJSONTyped(json, true);
    }
    if (instanceOfEquosResourceReference(json)) {
        return EquosResourceReferenceFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateEquosSessionRequestAvatarToJSON(json: any): any {
    return CreateEquosSessionRequestAvatarToJSONTyped(json, false);
}

export function CreateEquosSessionRequestAvatarToJSONTyped(value?: CreateEquosSessionRequestAvatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCreateEquosAvatarRequest(value)) {
        return CreateEquosAvatarRequestToJSON(value as CreateEquosAvatarRequest);
    }
    if (instanceOfEquosResourceReference(value)) {
        return EquosResourceReferenceToJSON(value as EquosResourceReference);
    }
    return {};
}

