/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosAvatarRequest
 */
export interface CreateEquosAvatarRequest {
    /**
     * Livekit identity of the avatar.
     * @type {string}
     * @memberof CreateEquosAvatarRequest
     */
    identity: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAvatarRequest
     */
    name: string;
    /**
     * Base64 data URL of the reference image.
     * @type {string}
     * @memberof CreateEquosAvatarRequest
     */
    refImage: string;
    /**
     * Optional agent ID to link with the avatar.
     * @type {object}
     * @memberof CreateEquosAvatarRequest
     */
    agentId: object;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosAvatarRequest
     */
    client?: object;
}

/**
 * Check if a given object implements the CreateEquosAvatarRequest interface.
 */
export function instanceOfCreateEquosAvatarRequest(value: object): value is CreateEquosAvatarRequest {
    if (!('identity' in value) || value['identity'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('refImage' in value) || value['refImage'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    return true;
}

export function CreateEquosAvatarRequestFromJSON(json: any): CreateEquosAvatarRequest {
    return CreateEquosAvatarRequestFromJSONTyped(json, false);
}

export function CreateEquosAvatarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosAvatarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'],
        'name': json['name'],
        'refImage': json['refImage'],
        'agentId': json['agentId'],
        'client': json['client'] == null ? undefined : json['client'],
    };
}

export function CreateEquosAvatarRequestToJSON(json: any): CreateEquosAvatarRequest {
    return CreateEquosAvatarRequestToJSONTyped(json, false);
}

export function CreateEquosAvatarRequestToJSONTyped(value?: CreateEquosAvatarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': value['identity'],
        'name': value['name'],
        'refImage': value['refImage'],
        'agentId': value['agentId'],
        'client': value['client'],
    };
}

