/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateEquosAgentRequest } from './CreateEquosAgentRequest';
import {
    instanceOfCreateEquosAgentRequest,
    CreateEquosAgentRequestFromJSON,
    CreateEquosAgentRequestFromJSONTyped,
    CreateEquosAgentRequestToJSON,
} from './CreateEquosAgentRequest';
import type { EquosResourceReference } from './EquosResourceReference';
import {
    instanceOfEquosResourceReference,
    EquosResourceReferenceFromJSON,
    EquosResourceReferenceFromJSONTyped,
    EquosResourceReferenceToJSON,
} from './EquosResourceReference';

/**
 * @type CreateEquosSessionRequestAgent
 * [Optional] Either provide an existing agent ID or create a new agent on the fly.
 * @export
 */
export type CreateEquosSessionRequestAgent = CreateEquosAgentRequest | EquosResourceReference;

export function CreateEquosSessionRequestAgentFromJSON(json: any): CreateEquosSessionRequestAgent {
    return CreateEquosSessionRequestAgentFromJSONTyped(json, false);
}

export function CreateEquosSessionRequestAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosSessionRequestAgent {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCreateEquosAgentRequest(json)) {
        return CreateEquosAgentRequestFromJSONTyped(json, true);
    }
    if (instanceOfEquosResourceReference(json)) {
        return EquosResourceReferenceFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateEquosSessionRequestAgentToJSON(json: any): any {
    return CreateEquosSessionRequestAgentToJSONTyped(json, false);
}

export function CreateEquosSessionRequestAgentToJSONTyped(value?: CreateEquosSessionRequestAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCreateEquosAgentRequest(value)) {
        return CreateEquosAgentRequestToJSON(value as CreateEquosAgentRequest);
    }
    if (instanceOfEquosResourceReference(value)) {
        return EquosResourceReferenceToJSON(value as EquosResourceReference);
    }
    return {};
}

