/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosConversation } from './EquosConversation';
import {
    EquosConversationFromJSON,
    EquosConversationFromJSONTyped,
    EquosConversationToJSON,
    EquosConversationToJSONTyped,
} from './EquosConversation';

/**
 * 
 * @export
 * @interface CreateEquosConversationResponse
 */
export interface CreateEquosConversationResponse {
    /**
     * 
     * @type {EquosConversation}
     * @memberof CreateEquosConversationResponse
     */
    conversation: EquosConversation;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosConversationResponse
     */
    remoteAgentAccessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosConversationResponse
     */
    consumerAccessToken?: string | null;
}

/**
 * Check if a given object implements the CreateEquosConversationResponse interface.
 */
export function instanceOfCreateEquosConversationResponse(value: object): value is CreateEquosConversationResponse {
    if (!('conversation' in value) || value['conversation'] === undefined) return false;
    return true;
}

export function CreateEquosConversationResponseFromJSON(json: any): CreateEquosConversationResponse {
    return CreateEquosConversationResponseFromJSONTyped(json, false);
}

export function CreateEquosConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversation': EquosConversationFromJSON(json['conversation']),
        'remoteAgentAccessToken': json['remoteAgentAccessToken'] == null ? undefined : json['remoteAgentAccessToken'],
        'consumerAccessToken': json['consumerAccessToken'] == null ? undefined : json['consumerAccessToken'],
    };
}

export function CreateEquosConversationResponseToJSON(json: any): CreateEquosConversationResponse {
    return CreateEquosConversationResponseToJSONTyped(json, false);
}

export function CreateEquosConversationResponseToJSONTyped(value?: CreateEquosConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation': EquosConversationToJSON(value['conversation']),
        'remoteAgentAccessToken': value['remoteAgentAccessToken'],
        'consumerAccessToken': value['consumerAccessToken'],
    };
}

