/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosConversationHost } from './EquosConversationHost';
import {
    EquosConversationHostFromJSON,
    EquosConversationHostFromJSONTyped,
    EquosConversationHostToJSON,
    EquosConversationHostToJSONTyped,
} from './EquosConversationHost';
import type { EquosParticipantIdentity } from './EquosParticipantIdentity';
import {
    EquosParticipantIdentityFromJSON,
    EquosParticipantIdentityFromJSONTyped,
    EquosParticipantIdentityToJSON,
    EquosParticipantIdentityToJSONTyped,
} from './EquosParticipantIdentity';

/**
 * 
 * @export
 * @interface CreateEquosConversationRequest
 */
export interface CreateEquosConversationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEquosConversationRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosConversationRequest
     */
    characterId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosConversationRequest
     */
    client?: string | null;
    /**
     * 
     * @type {EquosConversationHost}
     * @memberof CreateEquosConversationRequest
     */
    host?: EquosConversationHost | null;
    /**
     * 
     * @type {EquosParticipantIdentity}
     * @memberof CreateEquosConversationRequest
     */
    remoteAgent?: EquosParticipantIdentity | null;
    /**
     * 
     * @type {EquosParticipantIdentity}
     * @memberof CreateEquosConversationRequest
     */
    consumer?: EquosParticipantIdentity | null;
    /**
     * 
     * @type {number}
     * @memberof CreateEquosConversationRequest
     */
    maxSeconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosConversationRequest
     */
    promptCtx?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateEquosConversationRequest
     */
    promptTemplateVars?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the CreateEquosConversationRequest interface.
 */
export function instanceOfCreateEquosConversationRequest(value: object): value is CreateEquosConversationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('characterId' in value) || value['characterId'] === undefined) return false;
    return true;
}

export function CreateEquosConversationRequestFromJSON(json: any): CreateEquosConversationRequest {
    return CreateEquosConversationRequestFromJSONTyped(json, false);
}

export function CreateEquosConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'characterId': json['characterId'],
        'client': json['client'] == null ? undefined : json['client'],
        'host': json['host'] == null ? undefined : EquosConversationHostFromJSON(json['host']),
        'remoteAgent': json['remoteAgent'] == null ? undefined : EquosParticipantIdentityFromJSON(json['remoteAgent']),
        'consumer': json['consumer'] == null ? undefined : EquosParticipantIdentityFromJSON(json['consumer']),
        'maxSeconds': json['maxSeconds'] == null ? undefined : json['maxSeconds'],
        'promptCtx': json['promptCtx'] == null ? undefined : json['promptCtx'],
        'promptTemplateVars': json['promptTemplateVars'] == null ? undefined : json['promptTemplateVars'],
    };
}

export function CreateEquosConversationRequestToJSON(json: any): CreateEquosConversationRequest {
    return CreateEquosConversationRequestToJSONTyped(json, false);
}

export function CreateEquosConversationRequestToJSONTyped(value?: CreateEquosConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'characterId': value['characterId'],
        'client': value['client'],
        'host': EquosConversationHostToJSON(value['host']),
        'remoteAgent': EquosParticipantIdentityToJSON(value['remoteAgent']),
        'consumer': EquosParticipantIdentityToJSON(value['consumer']),
        'maxSeconds': value['maxSeconds'],
        'promptCtx': value['promptCtx'],
        'promptTemplateVars': value['promptTemplateVars'],
    };
}

