/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosCharacterRequest
 */
export interface CreateEquosCharacterRequest {
    /**
     * Client identifier associated with the character. This is useful to segment resources by client.
     * @type {object}
     * @memberof CreateEquosCharacterRequest
     */
    client?: object | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosCharacterRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosCharacterRequest
     */
    livekitIdentity: string;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosCharacterRequest
     */
    faceId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosCharacterRequest
     */
    voiceId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosCharacterRequest
     */
    brainId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosCharacterRequest
     */
    knowledgeBaseId?: object | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEquosCharacterRequest
     */
    search?: boolean;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosCharacterRequest
     */
    elevenlabsAgentId?: object | null;
}

/**
 * Check if a given object implements the CreateEquosCharacterRequest interface.
 */
export function instanceOfCreateEquosCharacterRequest(value: object): value is CreateEquosCharacterRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('livekitIdentity' in value) || value['livekitIdentity'] === undefined) return false;
    return true;
}

export function CreateEquosCharacterRequestFromJSON(json: any): CreateEquosCharacterRequest {
    return CreateEquosCharacterRequestFromJSONTyped(json, false);
}

export function CreateEquosCharacterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosCharacterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'] == null ? undefined : json['client'],
        'name': json['name'],
        'livekitIdentity': json['livekitIdentity'],
        'faceId': json['faceId'] == null ? undefined : json['faceId'],
        'voiceId': json['voiceId'] == null ? undefined : json['voiceId'],
        'brainId': json['brainId'] == null ? undefined : json['brainId'],
        'knowledgeBaseId': json['knowledgeBaseId'] == null ? undefined : json['knowledgeBaseId'],
        'search': json['search'] == null ? undefined : json['search'],
        'elevenlabsAgentId': json['elevenlabsAgentId'] == null ? undefined : json['elevenlabsAgentId'],
    };
}

export function CreateEquosCharacterRequestToJSON(json: any): CreateEquosCharacterRequest {
    return CreateEquosCharacterRequestToJSONTyped(json, false);
}

export function CreateEquosCharacterRequestToJSONTyped(value?: CreateEquosCharacterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
        'name': value['name'],
        'livekitIdentity': value['livekitIdentity'],
        'faceId': value['faceId'],
        'voiceId': value['voiceId'],
        'brainId': value['brainId'],
        'knowledgeBaseId': value['knowledgeBaseId'],
        'search': value['search'],
        'elevenlabsAgentId': value['elevenlabsAgentId'],
    };
}

