/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosFaceRequest
 */
export interface CreateEquosFaceRequest {
    /**
     * Client identifier associated with the face. This is useful to segment resources by client.
     * @type {object}
     * @memberof CreateEquosFaceRequest
     */
    client?: object | null;
    /**
     * Identity of the face in Equos Gallery.
     * @type {string}
     * @memberof CreateEquosFaceRequest
     */
    identity: CreateEquosFaceRequestIdentityEnum;
}


/**
 * @export
 */
export const CreateEquosFaceRequestIdentityEnum = {
    Byron: 'byron',
    Emily: 'emily',
    Marise: 'marise',
    Jenny: 'jenny',
    Isabelle: 'isabelle',
    William: 'william',
    Elaryon: 'elaryon',
    Stephen: 'stephen',
    Ryan: 'ryan'
} as const;
export type CreateEquosFaceRequestIdentityEnum = typeof CreateEquosFaceRequestIdentityEnum[keyof typeof CreateEquosFaceRequestIdentityEnum];


/**
 * Check if a given object implements the CreateEquosFaceRequest interface.
 */
export function instanceOfCreateEquosFaceRequest(value: object): value is CreateEquosFaceRequest {
    if (!('identity' in value) || value['identity'] === undefined) return false;
    return true;
}

export function CreateEquosFaceRequestFromJSON(json: any): CreateEquosFaceRequest {
    return CreateEquosFaceRequestFromJSONTyped(json, false);
}

export function CreateEquosFaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosFaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'] == null ? undefined : json['client'],
        'identity': json['identity'],
    };
}

export function CreateEquosFaceRequestToJSON(json: any): CreateEquosFaceRequest {
    return CreateEquosFaceRequestToJSONTyped(json, false);
}

export function CreateEquosFaceRequestToJSONTyped(value?: CreateEquosFaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
        'identity': value['identity'],
    };
}

