/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquosAgentRequest
 */
export interface CreateEquosAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    name?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateEquosAgentRequest
     */
    client?: object | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    provider: CreateEquosAgentRequestProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    model?: CreateEquosAgentRequestModelEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    voice?: CreateEquosAgentRequestVoiceEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    instructions?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    greetingMsg?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquosAgentRequest
     */
    remoteId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEquosAgentRequest
     */
    search?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEquosAgentRequest
     */
    emotions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEquosAgentRequest
     */
    memory?: boolean;
}


/**
 * @export
 */
export const CreateEquosAgentRequestProviderEnum = {
    Openai: 'openai',
    Gemini: 'gemini',
    Elevenlabs: 'elevenlabs'
} as const;
export type CreateEquosAgentRequestProviderEnum = typeof CreateEquosAgentRequestProviderEnum[keyof typeof CreateEquosAgentRequestProviderEnum];

/**
 * @export
 */
export const CreateEquosAgentRequestModelEnum = {
    Gemini25FlashNativeAudioPreview092025: 'gemini-2.5-flash-native-audio-preview-09-2025'
} as const;
export type CreateEquosAgentRequestModelEnum = typeof CreateEquosAgentRequestModelEnum[keyof typeof CreateEquosAgentRequestModelEnum];

/**
 * @export
 */
export const CreateEquosAgentRequestVoiceEnum = {
    Puck: 'Puck',
    Charon: 'Charon',
    Kore: 'Kore',
    Fenrir: 'Fenrir',
    Aoede: 'Aoede',
    Leda: 'Leda',
    Orus: 'Orus',
    Zephyr: 'Zephyr',
    Sulafat: 'Sulafat',
    Sadachbia: 'Sadachbia',
    Sadaltager: 'Sadaltager',
    Vindemiatrix: 'Vindemiatrix',
    Zubenelgenubi: 'Zubenelgenubi',
    Achird: 'Achird',
    Pulcherrima: 'Pulcherrima',
    Gacrux: 'Gacrux',
    Schedar: 'Schedar',
    Alnilam: 'Alnilam',
    Achernar: 'Achernar',
    Laomedeia: 'Laomedeia',
    Rasalgethi: 'Rasalgethi',
    Algenib: 'Algenib',
    Erinome: 'Erinome',
    Despina: 'Despina',
    Algieba: 'Algieba',
    Umbriel: 'Umbriel',
    Iapetus: 'Iapetus',
    Enceladus: 'Enceladus',
    Autonoe: 'Autonoe',
    Callirrhoe: 'Callirrhoe'
} as const;
export type CreateEquosAgentRequestVoiceEnum = typeof CreateEquosAgentRequestVoiceEnum[keyof typeof CreateEquosAgentRequestVoiceEnum];


/**
 * Check if a given object implements the CreateEquosAgentRequest interface.
 */
export function instanceOfCreateEquosAgentRequest(value: object): value is CreateEquosAgentRequest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function CreateEquosAgentRequestFromJSON(json: any): CreateEquosAgentRequest {
    return CreateEquosAgentRequestFromJSONTyped(json, false);
}

export function CreateEquosAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquosAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'client': json['client'] == null ? undefined : json['client'],
        'provider': json['provider'],
        'model': json['model'] == null ? undefined : json['model'],
        'voice': json['voice'] == null ? undefined : json['voice'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'greetingMsg': json['greetingMsg'] == null ? undefined : json['greetingMsg'],
        'remoteId': json['remoteId'] == null ? undefined : json['remoteId'],
        'search': json['search'] == null ? undefined : json['search'],
        'emotions': json['emotions'] == null ? undefined : json['emotions'],
        'memory': json['memory'] == null ? undefined : json['memory'],
    };
}

export function CreateEquosAgentRequestToJSON(json: any): CreateEquosAgentRequest {
    return CreateEquosAgentRequestToJSONTyped(json, false);
}

export function CreateEquosAgentRequestToJSONTyped(value?: CreateEquosAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'client': value['client'],
        'provider': value['provider'],
        'model': value['model'],
        'voice': value['voice'],
        'instructions': value['instructions'],
        'greetingMsg': value['greetingMsg'],
        'remoteId': value['remoteId'],
        'search': value['search'],
        'emotions': value['emotions'],
        'memory': value['memory'],
    };
}

