/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosConversationTranscriptMessage } from './EquosConversationTranscriptMessage';
import {
    EquosConversationTranscriptMessageFromJSON,
    EquosConversationTranscriptMessageFromJSONTyped,
    EquosConversationTranscriptMessageToJSON,
    EquosConversationTranscriptMessageToJSONTyped,
} from './EquosConversationTranscriptMessage';

/**
 * 
 * @export
 * @interface EquosConversation
 */
export interface EquosConversation {
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    status: EquosConversationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    room: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    serverUrl: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    remoteAgentName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    remoteAgentIdentity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    consumerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    consumerIdentity?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EquosConversation
     */
    charge: boolean;
    /**
     * 
     * @type {number}
     * @memberof EquosConversation
     */
    chargeBySecond: number;
    /**
     * 
     * @type {number}
     * @memberof EquosConversation
     */
    maxSeconds: number;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    promptCtx?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EquosConversation
     */
    promptTemplateVars?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<EquosConversationTranscriptMessage>}
     * @memberof EquosConversation
     */
    transcript?: Array<EquosConversationTranscriptMessage> | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosConversation
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosConversation
     */
    joinedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosConversation
     */
    endedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosConversation
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosConversation
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    characterId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversation
     */
    organizationId: string;
}


/**
 * @export
 */
export const EquosConversationStatusEnum = {
    Running: 'running',
    Blocked: 'blocked',
    Ended: 'ended',
    Error: 'error'
} as const;
export type EquosConversationStatusEnum = typeof EquosConversationStatusEnum[keyof typeof EquosConversationStatusEnum];


/**
 * Check if a given object implements the EquosConversation interface.
 */
export function instanceOfEquosConversation(value: object): value is EquosConversation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('room' in value) || value['room'] === undefined) return false;
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    if (!('charge' in value) || value['charge'] === undefined) return false;
    if (!('chargeBySecond' in value) || value['chargeBySecond'] === undefined) return false;
    if (!('maxSeconds' in value) || value['maxSeconds'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('characterId' in value) || value['characterId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function EquosConversationFromJSON(json: any): EquosConversation {
    return EquosConversationFromJSONTyped(json, false);
}

export function EquosConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosConversation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'client': json['client'] == null ? undefined : json['client'],
        'status': json['status'],
        'room': json['room'],
        'serverUrl': json['serverUrl'],
        'remoteAgentName': json['remoteAgentName'] == null ? undefined : json['remoteAgentName'],
        'remoteAgentIdentity': json['remoteAgentIdentity'] == null ? undefined : json['remoteAgentIdentity'],
        'consumerName': json['consumerName'] == null ? undefined : json['consumerName'],
        'consumerIdentity': json['consumerIdentity'] == null ? undefined : json['consumerIdentity'],
        'charge': json['charge'],
        'chargeBySecond': json['chargeBySecond'],
        'maxSeconds': json['maxSeconds'],
        'promptCtx': json['promptCtx'] == null ? undefined : json['promptCtx'],
        'promptTemplateVars': json['promptTemplateVars'] == null ? undefined : json['promptTemplateVars'],
        'transcript': json['transcript'] == null ? undefined : ((json['transcript'] as Array<any>).map(EquosConversationTranscriptMessageFromJSON)),
        'startedAt': (new Date(json['startedAt'])),
        'joinedAt': json['joinedAt'] == null ? undefined : (new Date(json['joinedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'characterId': json['characterId'],
        'organizationId': json['organizationId'],
    };
}

export function EquosConversationToJSON(json: any): EquosConversation {
    return EquosConversationToJSONTyped(json, false);
}

export function EquosConversationToJSONTyped(value?: EquosConversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'client': value['client'],
        'status': value['status'],
        'room': value['room'],
        'serverUrl': value['serverUrl'],
        'remoteAgentName': value['remoteAgentName'],
        'remoteAgentIdentity': value['remoteAgentIdentity'],
        'consumerName': value['consumerName'],
        'consumerIdentity': value['consumerIdentity'],
        'charge': value['charge'],
        'chargeBySecond': value['chargeBySecond'],
        'maxSeconds': value['maxSeconds'],
        'promptCtx': value['promptCtx'],
        'promptTemplateVars': value['promptTemplateVars'],
        'transcript': value['transcript'] == null ? undefined : ((value['transcript'] as Array<any>).map(EquosConversationTranscriptMessageToJSON)),
        'startedAt': value['startedAt'].toISOString(),
        'joinedAt': value['joinedAt'] == null ? value['joinedAt'] : value['joinedAt'].toISOString(),
        'endedAt': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'characterId': value['characterId'],
        'organizationId': value['organizationId'],
    };
}

