/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosAvatar
 */
export interface EquosAvatar {
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    identity: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    client?: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAvatar
     */
    thumbnailUrl: string;
    /**
     * 
     * @type {object}
     * @memberof EquosAvatar
     */
    agentId?: object;
    /**
     * 
     * @type {object}
     * @memberof EquosAvatar
     */
    agent?: object;
    /**
     * 
     * @type {Date}
     * @memberof EquosAvatar
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosAvatar
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosAvatar interface.
 */
export function instanceOfEquosAvatar(value: object): value is EquosAvatar {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('identity' in value) || value['identity'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosAvatarFromJSON(json: any): EquosAvatar {
    return EquosAvatarFromJSONTyped(json, false);
}

export function EquosAvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosAvatar {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'identity': json['identity'],
        'name': json['name'],
        'description': json['description'],
        'client': json['client'] == null ? undefined : json['client'],
        'thumbnailUrl': json['thumbnailUrl'],
        'agentId': json['agentId'] == null ? undefined : json['agentId'],
        'agent': json['agent'] == null ? undefined : json['agent'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosAvatarToJSON(json: any): EquosAvatar {
    return EquosAvatarToJSONTyped(json, false);
}

export function EquosAvatarToJSONTyped(value?: EquosAvatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'identity': value['identity'],
        'name': value['name'],
        'description': value['description'],
        'client': value['client'],
        'thumbnailUrl': value['thumbnailUrl'],
        'agentId': value['agentId'],
        'agent': value['agent'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

