/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosParticipantIdentity
 */
export interface EquosParticipantIdentity {
    /**
     * 
     * @type {string}
     * @memberof EquosParticipantIdentity
     */
    identity: string;
    /**
     * 
     * @type {string}
     * @memberof EquosParticipantIdentity
     */
    name: string;
}

/**
 * Check if a given object implements the EquosParticipantIdentity interface.
 */
export function instanceOfEquosParticipantIdentity(value: object): value is EquosParticipantIdentity {
    if (!('identity' in value) || value['identity'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EquosParticipantIdentityFromJSON(json: any): EquosParticipantIdentity {
    return EquosParticipantIdentityFromJSONTyped(json, false);
}

export function EquosParticipantIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosParticipantIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'],
        'name': json['name'],
    };
}

export function EquosParticipantIdentityToJSON(json: any): EquosParticipantIdentity {
    return EquosParticipantIdentityToJSONTyped(json, false);
}

export function EquosParticipantIdentityToJSONTyped(value?: EquosParticipantIdentity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': value['identity'],
        'name': value['name'],
    };
}

