/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosLimitResponse
 */
export interface EquosLimitResponse {
    /**
     * 
     * @type {string}
     * @memberof EquosLimitResponse
     */
    organizationId: string;
    /**
     * 
     * @type {number}
     * @memberof EquosLimitResponse
     */
    concurrent: number;
    /**
     * 
     * @type {number}
     * @memberof EquosLimitResponse
     */
    duration: number;
    /**
     * 
     * @type {boolean}
     * @memberof EquosLimitResponse
     */
    suspended: boolean;
    /**
     * 
     * @type {string}
     * @memberof EquosLimitResponse
     */
    reason?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosLimitResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosLimitResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosLimitResponse interface.
 */
export function instanceOfEquosLimitResponse(value: object): value is EquosLimitResponse {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('concurrent' in value) || value['concurrent'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('suspended' in value) || value['suspended'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosLimitResponseFromJSON(json: any): EquosLimitResponse {
    return EquosLimitResponseFromJSONTyped(json, false);
}

export function EquosLimitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosLimitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'],
        'concurrent': json['concurrent'],
        'duration': json['duration'],
        'suspended': json['suspended'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosLimitResponseToJSON(json: any): EquosLimitResponse {
    return EquosLimitResponseToJSONTyped(json, false);
}

export function EquosLimitResponseToJSONTyped(value?: EquosLimitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'concurrent': value['concurrent'],
        'duration': value['duration'],
        'suspended': value['suspended'],
        'reason': value['reason'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

