/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosDocument } from './EquosDocument';
import {
    EquosDocumentFromJSON,
    EquosDocumentFromJSONTyped,
    EquosDocumentToJSON,
    EquosDocumentToJSONTyped,
} from './EquosDocument';

/**
 * 
 * @export
 * @interface EquosKnowledgeBase
 */
export interface EquosKnowledgeBase {
    /**
     * 
     * @type {string}
     * @memberof EquosKnowledgeBase
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosKnowledgeBase
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosKnowledgeBase
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosKnowledgeBase
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EquosKnowledgeBase
     */
    client?: string;
    /**
     * 
     * @type {Array<EquosDocument>}
     * @memberof EquosKnowledgeBase
     */
    documents: Array<EquosDocument>;
    /**
     * 
     * @type {Date}
     * @memberof EquosKnowledgeBase
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosKnowledgeBase
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosKnowledgeBase interface.
 */
export function instanceOfEquosKnowledgeBase(value: object): value is EquosKnowledgeBase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosKnowledgeBaseFromJSON(json: any): EquosKnowledgeBase {
    return EquosKnowledgeBaseFromJSONTyped(json, false);
}

export function EquosKnowledgeBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosKnowledgeBase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'name': json['name'],
        'description': json['description'],
        'client': json['client'] == null ? undefined : json['client'],
        'documents': ((json['documents'] as Array<any>).map(EquosDocumentFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosKnowledgeBaseToJSON(json: any): EquosKnowledgeBase {
    return EquosKnowledgeBaseToJSONTyped(json, false);
}

export function EquosKnowledgeBaseToJSONTyped(value?: EquosKnowledgeBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'name': value['name'],
        'description': value['description'],
        'client': value['client'],
        'documents': ((value['documents'] as Array<any>).map(EquosDocumentToJSON)),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

