/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosSessionServer
 */
export interface EquosSessionServer {
    /**
     * The URL of the LiveKit server.
     * @type {string}
     * @memberof EquosSessionServer
     */
    serverUrl: string;
}

/**
 * Check if a given object implements the EquosSessionServer interface.
 */
export function instanceOfEquosSessionServer(value: object): value is EquosSessionServer {
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    return true;
}

export function EquosSessionServerFromJSON(json: any): EquosSessionServer {
    return EquosSessionServerFromJSONTyped(json, false);
}

export function EquosSessionServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosSessionServer {
    if (json == null) {
        return json;
    }
    return {
        
        'serverUrl': json['serverUrl'],
    };
}

export function EquosSessionServerToJSON(json: any): EquosSessionServer {
    return EquosSessionServerToJSONTyped(json, false);
}

export function EquosSessionServerToJSONTyped(value?: EquosSessionServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverUrl': value['serverUrl'],
    };
}

