/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosConversationTranscriptMessage
 */
export interface EquosConversationTranscriptMessage {
    /**
     * 
     * @type {string}
     * @memberof EquosConversationTranscriptMessage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversationTranscriptMessage
     */
    author: EquosConversationTranscriptMessageAuthorEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosConversationTranscriptMessage
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof EquosConversationTranscriptMessage
     */
    recordedAt: Date;
}


/**
 * @export
 */
export const EquosConversationTranscriptMessageAuthorEnum = {
    User: 'user',
    Character: 'character'
} as const;
export type EquosConversationTranscriptMessageAuthorEnum = typeof EquosConversationTranscriptMessageAuthorEnum[keyof typeof EquosConversationTranscriptMessageAuthorEnum];


/**
 * Check if a given object implements the EquosConversationTranscriptMessage interface.
 */
export function instanceOfEquosConversationTranscriptMessage(value: object): value is EquosConversationTranscriptMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('recordedAt' in value) || value['recordedAt'] === undefined) return false;
    return true;
}

export function EquosConversationTranscriptMessageFromJSON(json: any): EquosConversationTranscriptMessage {
    return EquosConversationTranscriptMessageFromJSONTyped(json, false);
}

export function EquosConversationTranscriptMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosConversationTranscriptMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'author': json['author'],
        'content': json['content'],
        'recordedAt': (new Date(json['recordedAt'])),
    };
}

export function EquosConversationTranscriptMessageToJSON(json: any): EquosConversationTranscriptMessage {
    return EquosConversationTranscriptMessageToJSONTyped(json, false);
}

export function EquosConversationTranscriptMessageToJSONTyped(value?: EquosConversationTranscriptMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'author': value['author'],
        'content': value['content'],
        'recordedAt': value['recordedAt'].toISOString(),
    };
}

