/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosDocument
 */
export interface EquosDocument {
    /**
     * 
     * @type {string}
     * @memberof EquosDocument
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosDocument
     */
    knowledgeBaseId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosDocument
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosDocument
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof EquosDocument
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof EquosDocument
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof EquosDocument
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosDocument
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosDocument interface.
 */
export function instanceOfEquosDocument(value: object): value is EquosDocument {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('knowledgeBaseId' in value) || value['knowledgeBaseId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosDocumentFromJSON(json: any): EquosDocument {
    return EquosDocumentFromJSONTyped(json, false);
}

export function EquosDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'knowledgeBaseId': json['knowledgeBaseId'],
        'name': json['name'],
        'description': json['description'],
        'size': json['size'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosDocumentToJSON(json: any): EquosDocument {
    return EquosDocumentToJSONTyped(json, false);
}

export function EquosDocumentToJSONTyped(value?: EquosDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'knowledgeBaseId': value['knowledgeBaseId'],
        'name': value['name'],
        'description': value['description'],
        'size': value['size'],
        'status': value['status'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

