/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosFace
 */
export interface EquosFace {
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    identity: EquosFaceIdentityEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    thumbnailUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    referenceImgUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosFace
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosFace
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const EquosFaceIdentityEnum = {
    Byron: 'byron',
    Emily: 'emily',
    Marise: 'marise',
    Jenny: 'jenny',
    Isabelle: 'isabelle',
    William: 'william',
    Elaryon: 'elaryon',
    Stephen: 'stephen',
    Ryan: 'ryan'
} as const;
export type EquosFaceIdentityEnum = typeof EquosFaceIdentityEnum[keyof typeof EquosFaceIdentityEnum];


/**
 * Check if a given object implements the EquosFace interface.
 */
export function instanceOfEquosFace(value: object): value is EquosFace {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('identity' in value) || value['identity'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosFaceFromJSON(json: any): EquosFace {
    return EquosFaceFromJSONTyped(json, false);
}

export function EquosFaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosFace {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'identity': json['identity'],
        'organizationId': json['organizationId'],
        'client': json['client'] == null ? undefined : json['client'],
        'description': json['description'] == null ? undefined : json['description'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'referenceImgUrl': json['referenceImgUrl'] == null ? undefined : json['referenceImgUrl'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosFaceToJSON(json: any): EquosFace {
    return EquosFaceToJSONTyped(json, false);
}

export function EquosFaceToJSONTyped(value?: EquosFace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'identity': value['identity'],
        'organizationId': value['organizationId'],
        'client': value['client'],
        'description': value['description'],
        'thumbnailUrl': value['thumbnailUrl'],
        'referenceImgUrl': value['referenceImgUrl'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

