/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosFace } from './EquosFace';
import {
    EquosFaceFromJSON,
    EquosFaceFromJSONTyped,
    EquosFaceToJSON,
    EquosFaceToJSONTyped,
} from './EquosFace';
import type { EquosKnowledgeBase } from './EquosKnowledgeBase';
import {
    EquosKnowledgeBaseFromJSON,
    EquosKnowledgeBaseFromJSONTyped,
    EquosKnowledgeBaseToJSON,
    EquosKnowledgeBaseToJSONTyped,
} from './EquosKnowledgeBase';
import type { EquosBrain } from './EquosBrain';
import {
    EquosBrainFromJSON,
    EquosBrainFromJSONTyped,
    EquosBrainToJSON,
    EquosBrainToJSONTyped,
} from './EquosBrain';
import type { EquosVoice } from './EquosVoice';
import {
    EquosVoiceFromJSON,
    EquosVoiceFromJSONTyped,
    EquosVoiceToJSON,
    EquosVoiceToJSONTyped,
} from './EquosVoice';

/**
 * 
 * @export
 * @interface EquosCharacter
 */
export interface EquosCharacter {
    /**
     * 
     * @type {string}
     * @memberof EquosCharacter
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosCharacter
     */
    organizationId: string;
    /**
     * 
     * @type {object}
     * @memberof EquosCharacter
     */
    client?: object | null;
    /**
     * 
     * @type {string}
     * @memberof EquosCharacter
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosCharacter
     */
    livekitIdentity: string;
    /**
     * 
     * @type {boolean}
     * @memberof EquosCharacter
     */
    search: boolean;
    /**
     * 
     * @type {object}
     * @memberof EquosCharacter
     */
    elevenlabsAgentId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosCharacter
     */
    faceId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosCharacter
     */
    voiceId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosCharacter
     */
    brainId?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosCharacter
     */
    knowledgeBaseId?: object | null;
    /**
     * 
     * @type {EquosFace}
     * @memberof EquosCharacter
     */
    face?: EquosFace | null;
    /**
     * 
     * @type {EquosVoice}
     * @memberof EquosCharacter
     */
    voice?: EquosVoice | null;
    /**
     * 
     * @type {EquosBrain}
     * @memberof EquosCharacter
     */
    brain?: EquosBrain | null;
    /**
     * 
     * @type {EquosKnowledgeBase}
     * @memberof EquosCharacter
     */
    knowledgeBase?: EquosKnowledgeBase | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosCharacter
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosCharacter
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosCharacter interface.
 */
export function instanceOfEquosCharacter(value: object): value is EquosCharacter {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('livekitIdentity' in value) || value['livekitIdentity'] === undefined) return false;
    if (!('search' in value) || value['search'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosCharacterFromJSON(json: any): EquosCharacter {
    return EquosCharacterFromJSONTyped(json, false);
}

export function EquosCharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosCharacter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'client': json['client'] == null ? undefined : json['client'],
        'name': json['name'],
        'livekitIdentity': json['livekitIdentity'],
        'search': json['search'],
        'elevenlabsAgentId': json['elevenlabsAgentId'] == null ? undefined : json['elevenlabsAgentId'],
        'faceId': json['faceId'] == null ? undefined : json['faceId'],
        'voiceId': json['voiceId'] == null ? undefined : json['voiceId'],
        'brainId': json['brainId'] == null ? undefined : json['brainId'],
        'knowledgeBaseId': json['knowledgeBaseId'] == null ? undefined : json['knowledgeBaseId'],
        'face': json['face'] == null ? undefined : EquosFaceFromJSON(json['face']),
        'voice': json['voice'] == null ? undefined : EquosVoiceFromJSON(json['voice']),
        'brain': json['brain'] == null ? undefined : EquosBrainFromJSON(json['brain']),
        'knowledgeBase': json['knowledgeBase'] == null ? undefined : EquosKnowledgeBaseFromJSON(json['knowledgeBase']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosCharacterToJSON(json: any): EquosCharacter {
    return EquosCharacterToJSONTyped(json, false);
}

export function EquosCharacterToJSONTyped(value?: EquosCharacter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'client': value['client'],
        'name': value['name'],
        'livekitIdentity': value['livekitIdentity'],
        'search': value['search'],
        'elevenlabsAgentId': value['elevenlabsAgentId'],
        'faceId': value['faceId'],
        'voiceId': value['voiceId'],
        'brainId': value['brainId'],
        'knowledgeBaseId': value['knowledgeBaseId'],
        'face': EquosFaceToJSON(value['face']),
        'voice': EquosVoiceToJSON(value['voice']),
        'brain': EquosBrainToJSON(value['brain']),
        'knowledgeBase': EquosKnowledgeBaseToJSON(value['knowledgeBase']),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

