/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosResourceReference } from './EquosResourceReference';
import {
    EquosResourceReferenceFromJSON,
    EquosResourceReferenceFromJSONTyped,
    EquosResourceReferenceToJSON,
    EquosResourceReferenceToJSONTyped,
} from './EquosResourceReference';
import type { EquosAgent } from './EquosAgent';
import {
    EquosAgentFromJSON,
    EquosAgentFromJSONTyped,
    EquosAgentToJSON,
    EquosAgentToJSONTyped,
} from './EquosAgent';
import type { EquosAvatar } from './EquosAvatar';
import {
    EquosAvatarFromJSON,
    EquosAvatarFromJSONTyped,
    EquosAvatarToJSON,
    EquosAvatarToJSONTyped,
} from './EquosAvatar';
import type { EquosSessionServer } from './EquosSessionServer';
import {
    EquosSessionServerFromJSON,
    EquosSessionServerFromJSONTyped,
    EquosSessionServerToJSON,
    EquosSessionServerToJSONTyped,
} from './EquosSessionServer';

/**
 * 
 * @export
 * @interface EquosSession
 */
export interface EquosSession {
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    organizationId: string;
    /**
     * 
     * @type {boolean}
     * @memberof EquosSession
     */
    freemium: boolean;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    client?: string;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof EquosSession
     */
    maxDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    additionalCtx?: string;
    /**
     * 
     * @type {object}
     * @memberof EquosSession
     */
    templateVars?: object;
    /**
     * 
     * @type {EquosSessionServer}
     * @memberof EquosSession
     */
    host: EquosSessionServer;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    avatarId?: string;
    /**
     * 
     * @type {EquosAvatar}
     * @memberof EquosSession
     */
    avatar: EquosAvatar;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    agentId?: string;
    /**
     * 
     * @type {EquosAgent}
     * @memberof EquosSession
     */
    agent?: EquosAgent | null;
    /**
     * 
     * @type {string}
     * @memberof EquosSession
     */
    knowledgeBaseId?: string;
    /**
     * 
     * @type {EquosResourceReference}
     * @memberof EquosSession
     */
    knowledgeBase?: EquosResourceReference;
    /**
     * 
     * @type {object}
     * @memberof EquosSession
     */
    remoteAgentIdentity?: object;
    /**
     * 
     * @type {object}
     * @memberof EquosSession
     */
    transcript?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosSession
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosSession
     */
    endedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosSession
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosSession
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosSession interface.
 */
export function instanceOfEquosSession(value: object): value is EquosSession {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('freemium' in value) || value['freemium'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosSessionFromJSON(json: any): EquosSession {
    return EquosSessionFromJSONTyped(json, false);
}

export function EquosSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosSession {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'freemium': json['freemium'],
        'name': json['name'],
        'provider': json['provider'],
        'client': json['client'] == null ? undefined : json['client'],
        'status': json['status'],
        'maxDuration': json['maxDuration'] == null ? undefined : json['maxDuration'],
        'additionalCtx': json['additionalCtx'] == null ? undefined : json['additionalCtx'],
        'templateVars': json['templateVars'] == null ? undefined : json['templateVars'],
        'host': EquosSessionServerFromJSON(json['host']),
        'avatarId': json['avatarId'] == null ? undefined : json['avatarId'],
        'avatar': EquosAvatarFromJSON(json['avatar']),
        'agentId': json['agentId'] == null ? undefined : json['agentId'],
        'agent': json['agent'] == null ? undefined : EquosAgentFromJSON(json['agent']),
        'knowledgeBaseId': json['knowledgeBaseId'] == null ? undefined : json['knowledgeBaseId'],
        'knowledgeBase': json['knowledgeBase'] == null ? undefined : EquosResourceReferenceFromJSON(json['knowledgeBase']),
        'remoteAgentIdentity': json['remoteAgentIdentity'] == null ? undefined : json['remoteAgentIdentity'],
        'transcript': json['transcript'] == null ? undefined : json['transcript'],
        'startedAt': (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosSessionToJSON(json: any): EquosSession {
    return EquosSessionToJSONTyped(json, false);
}

export function EquosSessionToJSONTyped(value?: EquosSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'freemium': value['freemium'],
        'name': value['name'],
        'provider': value['provider'],
        'client': value['client'],
        'status': value['status'],
        'maxDuration': value['maxDuration'],
        'additionalCtx': value['additionalCtx'],
        'templateVars': value['templateVars'],
        'host': EquosSessionServerToJSON(value['host']),
        'avatarId': value['avatarId'],
        'avatar': EquosAvatarToJSON(value['avatar']),
        'agentId': value['agentId'],
        'agent': EquosAgentToJSON(value['agent']),
        'knowledgeBaseId': value['knowledgeBaseId'],
        'knowledgeBase': EquosResourceReferenceToJSON(value['knowledgeBase']),
        'remoteAgentIdentity': value['remoteAgentIdentity'],
        'transcript': value['transcript'],
        'startedAt': value['startedAt'].toISOString(),
        'endedAt': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

