/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosAgent
 */
export interface EquosAgent {
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    provider: EquosAgentProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    client?: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    model?: EquosAgentModelEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    voice?: EquosAgentVoiceEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    instructions?: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    greetingMsg?: string;
    /**
     * 
     * @type {string}
     * @memberof EquosAgent
     */
    remoteId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EquosAgent
     */
    search: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EquosAgent
     */
    emotions: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EquosAgent
     */
    memory: boolean;
    /**
     * 
     * @type {Date}
     * @memberof EquosAgent
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosAgent
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const EquosAgentProviderEnum = {
    Openai: 'openai',
    Gemini: 'gemini',
    Elevenlabs: 'elevenlabs'
} as const;
export type EquosAgentProviderEnum = typeof EquosAgentProviderEnum[keyof typeof EquosAgentProviderEnum];

/**
 * @export
 */
export const EquosAgentModelEnum = {
    Gemini25FlashNativeAudioPreview092025: 'gemini-2.5-flash-native-audio-preview-09-2025',
    Gpt4oRealtimePreview: 'gpt-4o-realtime-preview',
    GptRealtime: 'gpt-realtime'
} as const;
export type EquosAgentModelEnum = typeof EquosAgentModelEnum[keyof typeof EquosAgentModelEnum];

/**
 * @export
 */
export const EquosAgentVoiceEnum = {
    Puck: 'Puck',
    Charon: 'Charon',
    Kore: 'Kore',
    Fenrir: 'Fenrir',
    Aoede: 'Aoede',
    Leda: 'Leda',
    Orus: 'Orus',
    Zephyr: 'Zephyr',
    Sulafat: 'Sulafat',
    Sadachbia: 'Sadachbia',
    Sadaltager: 'Sadaltager',
    Vindemiatrix: 'Vindemiatrix',
    Zubenelgenubi: 'Zubenelgenubi',
    Achird: 'Achird',
    Pulcherrima: 'Pulcherrima',
    Gacrux: 'Gacrux',
    Schedar: 'Schedar',
    Alnilam: 'Alnilam',
    Achernar: 'Achernar',
    Laomedeia: 'Laomedeia',
    Rasalgethi: 'Rasalgethi',
    Algenib: 'Algenib',
    Erinome: 'Erinome',
    Despina: 'Despina',
    Algieba: 'Algieba',
    Umbriel: 'Umbriel',
    Iapetus: 'Iapetus',
    Enceladus: 'Enceladus',
    Autonoe: 'Autonoe',
    Callirrhoe: 'Callirrhoe',
    Alloy: 'alloy',
    Marin: 'marin',
    Cedar: 'cedar',
    Ash: 'ash',
    Ballad: 'ballad',
    Coral: 'coral',
    Echo: 'echo',
    Sage: 'sage',
    Shimmer: 'shimmer',
    Verse: 'verse'
} as const;
export type EquosAgentVoiceEnum = typeof EquosAgentVoiceEnum[keyof typeof EquosAgentVoiceEnum];


/**
 * Check if a given object implements the EquosAgent interface.
 */
export function instanceOfEquosAgent(value: object): value is EquosAgent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('search' in value) || value['search'] === undefined) return false;
    if (!('emotions' in value) || value['emotions'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosAgentFromJSON(json: any): EquosAgent {
    return EquosAgentFromJSONTyped(json, false);
}

export function EquosAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'name': json['name'] == null ? undefined : json['name'],
        'provider': json['provider'],
        'client': json['client'] == null ? undefined : json['client'],
        'model': json['model'] == null ? undefined : json['model'],
        'voice': json['voice'] == null ? undefined : json['voice'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'greetingMsg': json['greetingMsg'] == null ? undefined : json['greetingMsg'],
        'remoteId': json['remoteId'] == null ? undefined : json['remoteId'],
        'search': json['search'],
        'emotions': json['emotions'],
        'memory': json['memory'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosAgentToJSON(json: any): EquosAgent {
    return EquosAgentToJSONTyped(json, false);
}

export function EquosAgentToJSONTyped(value?: EquosAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'name': value['name'],
        'provider': value['provider'],
        'client': value['client'],
        'model': value['model'],
        'voice': value['voice'],
        'instructions': value['instructions'],
        'greetingMsg': value['greetingMsg'],
        'remoteId': value['remoteId'],
        'search': value['search'],
        'emotions': value['emotions'],
        'memory': value['memory'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

