/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosConversationHost
 */
export interface EquosConversationHost {
    /**
     * 
     * @type {string}
     * @memberof EquosConversationHost
     */
    serverUrl: string;
    /**
     * 
     * @type {string}
     * @memberof EquosConversationHost
     */
    accessToken: string;
}

/**
 * Check if a given object implements the EquosConversationHost interface.
 */
export function instanceOfEquosConversationHost(value: object): value is EquosConversationHost {
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function EquosConversationHostFromJSON(json: any): EquosConversationHost {
    return EquosConversationHostFromJSONTyped(json, false);
}

export function EquosConversationHostFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosConversationHost {
    if (json == null) {
        return json;
    }
    return {
        
        'serverUrl': json['serverUrl'],
        'accessToken': json['accessToken'],
    };
}

export function EquosConversationHostToJSON(json: any): EquosConversationHost {
    return EquosConversationHostToJSONTyped(json, false);
}

export function EquosConversationHostToJSONTyped(value?: EquosConversationHost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverUrl': value['serverUrl'],
        'accessToken': value['accessToken'],
    };
}

