/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosFace
 */
export interface EquosFace {
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    status: EquosFaceStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EquosFace
     */
    organizationId: string;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    client?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    description?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    thumbnailUrl?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    thumbnailNoBgUrl?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    referenceImgUrl?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    referenceImgNoBgUrl?: object | null;
    /**
     * 
     * @type {object}
     * @memberof EquosFace
     */
    videoUrl?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof EquosFace
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosFace
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const EquosFaceStatusEnum = {
    Processing: 'processing',
    Ready: 'ready',
    Error: 'error'
} as const;
export type EquosFaceStatusEnum = typeof EquosFaceStatusEnum[keyof typeof EquosFaceStatusEnum];


/**
 * Check if a given object implements the EquosFace interface.
 */
export function instanceOfEquosFace(value: object): value is EquosFace {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosFaceFromJSON(json: any): EquosFace {
    return EquosFaceFromJSONTyped(json, false);
}

export function EquosFaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosFace {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'organizationId': json['organizationId'],
        'client': json['client'] == null ? undefined : json['client'],
        'description': json['description'] == null ? undefined : json['description'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'thumbnailNoBgUrl': json['thumbnailNoBgUrl'] == null ? undefined : json['thumbnailNoBgUrl'],
        'referenceImgUrl': json['referenceImgUrl'] == null ? undefined : json['referenceImgUrl'],
        'referenceImgNoBgUrl': json['referenceImgNoBgUrl'] == null ? undefined : json['referenceImgNoBgUrl'],
        'videoUrl': json['videoUrl'] == null ? undefined : json['videoUrl'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosFaceToJSON(json: any): EquosFace {
    return EquosFaceToJSONTyped(json, false);
}

export function EquosFaceToJSONTyped(value?: EquosFace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'organizationId': value['organizationId'],
        'client': value['client'],
        'description': value['description'],
        'thumbnailUrl': value['thumbnailUrl'],
        'thumbnailNoBgUrl': value['thumbnailNoBgUrl'],
        'referenceImgUrl': value['referenceImgUrl'],
        'referenceImgNoBgUrl': value['referenceImgNoBgUrl'],
        'videoUrl': value['videoUrl'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

