/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosVoice
 */
export interface EquosVoice {
    /**
     * 
     * @type {string}
     * @memberof EquosVoice
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosVoice
     */
    organizationId: string;
    /**
     * 
     * @type {object}
     * @memberof EquosVoice
     */
    client?: object | null;
    /**
     * 
     * @type {string}
     * @memberof EquosVoice
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosVoice
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EquosVoice
     */
    sampleUrl: string;
    /**
     * 
     * @type {string}
     * @memberof EquosVoice
     */
    voiceId: string;
    /**
     * 
     * @type {Date}
     * @memberof EquosVoice
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosVoice
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosVoice interface.
 */
export function instanceOfEquosVoice(value: object): value is EquosVoice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('sampleUrl' in value) || value['sampleUrl'] === undefined) return false;
    if (!('voiceId' in value) || value['voiceId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosVoiceFromJSON(json: any): EquosVoice {
    return EquosVoiceFromJSONTyped(json, false);
}

export function EquosVoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosVoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'client': json['client'] == null ? undefined : json['client'],
        'name': json['name'],
        'description': json['description'],
        'sampleUrl': json['sampleUrl'],
        'voiceId': json['voiceId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosVoiceToJSON(json: any): EquosVoice {
    return EquosVoiceToJSONTyped(json, false);
}

export function EquosVoiceToJSONTyped(value?: EquosVoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'client': value['client'],
        'name': value['name'],
        'description': value['description'],
        'sampleUrl': value['sampleUrl'],
        'voiceId': value['voiceId'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

