/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosResourceReference
 */
export interface EquosResourceReference {
    /**
     * 
     * @type {string}
     * @memberof EquosResourceReference
     */
    id: string;
}

/**
 * Check if a given object implements the EquosResourceReference interface.
 */
export function instanceOfEquosResourceReference(value: object): value is EquosResourceReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function EquosResourceReferenceFromJSON(json: any): EquosResourceReference {
    return EquosResourceReferenceFromJSONTyped(json, false);
}

export function EquosResourceReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosResourceReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function EquosResourceReferenceToJSON(json: any): EquosResourceReference {
    return EquosResourceReferenceToJSONTyped(json, false);
}

export function EquosResourceReferenceToJSONTyped(value?: EquosResourceReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

