/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosBrain
 */
export interface EquosBrain {
    /**
     * 
     * @type {string}
     * @memberof EquosBrain
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EquosBrain
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquosBrain
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquosBrain
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquosBrain
     */
    instructions: string;
    /**
     * 
     * @type {string}
     * @memberof EquosBrain
     */
    greetingMessage: string;
    /**
     * 
     * @type {Date}
     * @memberof EquosBrain
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquosBrain
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquosBrain interface.
 */
export function instanceOfEquosBrain(value: object): value is EquosBrain {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('greetingMessage' in value) || value['greetingMessage'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EquosBrainFromJSON(json: any): EquosBrain {
    return EquosBrainFromJSONTyped(json, false);
}

export function EquosBrainFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosBrain {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'client': json['client'] == null ? undefined : json['client'],
        'name': json['name'],
        'instructions': json['instructions'],
        'greetingMessage': json['greetingMessage'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquosBrainToJSON(json: any): EquosBrain {
    return EquosBrainToJSONTyped(json, false);
}

export function EquosBrainToJSONTyped(value?: EquosBrain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'client': value['client'],
        'name': value['name'],
        'instructions': value['instructions'],
        'greetingMessage': value['greetingMessage'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

