/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquosSessionHost
 */
export interface EquosSessionHost {
    /**
     * The URL of the LiveKit server.
     * @type {string}
     * @memberof EquosSessionHost
     */
    serverUrl: string;
    /**
     * The access token for the avatar to join the room.
     * @type {string}
     * @memberof EquosSessionHost
     */
    accessToken: string;
}

/**
 * Check if a given object implements the EquosSessionHost interface.
 */
export function instanceOfEquosSessionHost(value: object): value is EquosSessionHost {
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function EquosSessionHostFromJSON(json: any): EquosSessionHost {
    return EquosSessionHostFromJSONTyped(json, false);
}

export function EquosSessionHostFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquosSessionHost {
    if (json == null) {
        return json;
    }
    return {
        
        'serverUrl': json['serverUrl'],
        'accessToken': json['accessToken'],
    };
}

export function EquosSessionHostToJSON(json: any): EquosSessionHost {
    return EquosSessionHostToJSONTyped(json, false);
}

export function EquosSessionHostToJSONTyped(value?: EquosSessionHost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverUrl': value['serverUrl'],
        'accessToken': value['accessToken'],
    };
}

