/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosFace } from './EquosFace';
import {
    EquosFaceFromJSON,
    EquosFaceFromJSONTyped,
    EquosFaceToJSON,
    EquosFaceToJSONTyped,
} from './EquosFace';

/**
 * 
 * @export
 * @interface ListEquosFacesResponse
 */
export interface ListEquosFacesResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosFacesResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosFacesResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosFacesResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosFace>}
     * @memberof ListEquosFacesResponse
     */
    faces: Array<EquosFace>;
}

/**
 * Check if a given object implements the ListEquosFacesResponse interface.
 */
export function instanceOfListEquosFacesResponse(value: object): value is ListEquosFacesResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('faces' in value) || value['faces'] === undefined) return false;
    return true;
}

export function ListEquosFacesResponseFromJSON(json: any): ListEquosFacesResponse {
    return ListEquosFacesResponseFromJSONTyped(json, false);
}

export function ListEquosFacesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosFacesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'faces': ((json['faces'] as Array<any>).map(EquosFaceFromJSON)),
    };
}

export function ListEquosFacesResponseToJSON(json: any): ListEquosFacesResponse {
    return ListEquosFacesResponseToJSONTyped(json, false);
}

export function ListEquosFacesResponseToJSONTyped(value?: ListEquosFacesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'faces': ((value['faces'] as Array<any>).map(EquosFaceToJSON)),
    };
}

