/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosCharacter } from './EquosCharacter';
import {
    EquosCharacterFromJSON,
    EquosCharacterFromJSONTyped,
    EquosCharacterToJSON,
    EquosCharacterToJSONTyped,
} from './EquosCharacter';

/**
 * 
 * @export
 * @interface ListEquosCharactersResponse
 */
export interface ListEquosCharactersResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosCharactersResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosCharactersResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosCharactersResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosCharacter>}
     * @memberof ListEquosCharactersResponse
     */
    characters: Array<EquosCharacter>;
}

/**
 * Check if a given object implements the ListEquosCharactersResponse interface.
 */
export function instanceOfListEquosCharactersResponse(value: object): value is ListEquosCharactersResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('characters' in value) || value['characters'] === undefined) return false;
    return true;
}

export function ListEquosCharactersResponseFromJSON(json: any): ListEquosCharactersResponse {
    return ListEquosCharactersResponseFromJSONTyped(json, false);
}

export function ListEquosCharactersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosCharactersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'characters': ((json['characters'] as Array<any>).map(EquosCharacterFromJSON)),
    };
}

export function ListEquosCharactersResponseToJSON(json: any): ListEquosCharactersResponse {
    return ListEquosCharactersResponseToJSONTyped(json, false);
}

export function ListEquosCharactersResponseToJSONTyped(value?: ListEquosCharactersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'characters': ((value['characters'] as Array<any>).map(EquosCharacterToJSON)),
    };
}

