/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosSession } from './EquosSession';
import {
    EquosSessionFromJSON,
    EquosSessionFromJSONTyped,
    EquosSessionToJSON,
    EquosSessionToJSONTyped,
} from './EquosSession';

/**
 * 
 * @export
 * @interface ListEquosSessionsResponse
 */
export interface ListEquosSessionsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosSessionsResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosSessionsResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosSessionsResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosSession>}
     * @memberof ListEquosSessionsResponse
     */
    sessions: Array<EquosSession>;
}

/**
 * Check if a given object implements the ListEquosSessionsResponse interface.
 */
export function instanceOfListEquosSessionsResponse(value: object): value is ListEquosSessionsResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function ListEquosSessionsResponseFromJSON(json: any): ListEquosSessionsResponse {
    return ListEquosSessionsResponseFromJSONTyped(json, false);
}

export function ListEquosSessionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosSessionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'sessions': ((json['sessions'] as Array<any>).map(EquosSessionFromJSON)),
    };
}

export function ListEquosSessionsResponseToJSON(json: any): ListEquosSessionsResponse {
    return ListEquosSessionsResponseToJSONTyped(json, false);
}

export function ListEquosSessionsResponseToJSONTyped(value?: ListEquosSessionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'sessions': ((value['sessions'] as Array<any>).map(EquosSessionToJSON)),
    };
}

