/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosAvatar } from './EquosAvatar';
import {
    EquosAvatarFromJSON,
    EquosAvatarFromJSONTyped,
    EquosAvatarToJSON,
    EquosAvatarToJSONTyped,
} from './EquosAvatar';

/**
 * 
 * @export
 * @interface ListEquosAvatarsResponse
 */
export interface ListEquosAvatarsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosAvatarsResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosAvatarsResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosAvatarsResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosAvatar>}
     * @memberof ListEquosAvatarsResponse
     */
    avatars: Array<EquosAvatar>;
}

/**
 * Check if a given object implements the ListEquosAvatarsResponse interface.
 */
export function instanceOfListEquosAvatarsResponse(value: object): value is ListEquosAvatarsResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('avatars' in value) || value['avatars'] === undefined) return false;
    return true;
}

export function ListEquosAvatarsResponseFromJSON(json: any): ListEquosAvatarsResponse {
    return ListEquosAvatarsResponseFromJSONTyped(json, false);
}

export function ListEquosAvatarsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosAvatarsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'avatars': ((json['avatars'] as Array<any>).map(EquosAvatarFromJSON)),
    };
}

export function ListEquosAvatarsResponseToJSON(json: any): ListEquosAvatarsResponse {
    return ListEquosAvatarsResponseToJSONTyped(json, false);
}

export function ListEquosAvatarsResponseToJSONTyped(value?: ListEquosAvatarsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'avatars': ((value['avatars'] as Array<any>).map(EquosAvatarToJSON)),
    };
}

