/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosConversation } from './EquosConversation';
import {
    EquosConversationFromJSON,
    EquosConversationFromJSONTyped,
    EquosConversationToJSON,
    EquosConversationToJSONTyped,
} from './EquosConversation';

/**
 * 
 * @export
 * @interface ListEquosConversationsResponse
 */
export interface ListEquosConversationsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosConversationsResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosConversationsResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosConversationsResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosConversation>}
     * @memberof ListEquosConversationsResponse
     */
    conversations: Array<EquosConversation>;
}

/**
 * Check if a given object implements the ListEquosConversationsResponse interface.
 */
export function instanceOfListEquosConversationsResponse(value: object): value is ListEquosConversationsResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('conversations' in value) || value['conversations'] === undefined) return false;
    return true;
}

export function ListEquosConversationsResponseFromJSON(json: any): ListEquosConversationsResponse {
    return ListEquosConversationsResponseFromJSONTyped(json, false);
}

export function ListEquosConversationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosConversationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'conversations': ((json['conversations'] as Array<any>).map(EquosConversationFromJSON)),
    };
}

export function ListEquosConversationsResponseToJSON(json: any): ListEquosConversationsResponse {
    return ListEquosConversationsResponseToJSONTyped(json, false);
}

export function ListEquosConversationsResponseToJSONTyped(value?: ListEquosConversationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'conversations': ((value['conversations'] as Array<any>).map(EquosConversationToJSON)),
    };
}

