/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosVoice } from './EquosVoice';
import {
    EquosVoiceFromJSON,
    EquosVoiceFromJSONTyped,
    EquosVoiceToJSON,
    EquosVoiceToJSONTyped,
} from './EquosVoice';

/**
 * 
 * @export
 * @interface ListEquosVoicesResponse
 */
export interface ListEquosVoicesResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosVoicesResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosVoicesResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosVoicesResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosVoice>}
     * @memberof ListEquosVoicesResponse
     */
    voices: Array<EquosVoice>;
}

/**
 * Check if a given object implements the ListEquosVoicesResponse interface.
 */
export function instanceOfListEquosVoicesResponse(value: object): value is ListEquosVoicesResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('voices' in value) || value['voices'] === undefined) return false;
    return true;
}

export function ListEquosVoicesResponseFromJSON(json: any): ListEquosVoicesResponse {
    return ListEquosVoicesResponseFromJSONTyped(json, false);
}

export function ListEquosVoicesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosVoicesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'voices': ((json['voices'] as Array<any>).map(EquosVoiceFromJSON)),
    };
}

export function ListEquosVoicesResponseToJSON(json: any): ListEquosVoicesResponse {
    return ListEquosVoicesResponseToJSONTyped(json, false);
}

export function ListEquosVoicesResponseToJSONTyped(value?: ListEquosVoicesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'voices': ((value['voices'] as Array<any>).map(EquosVoiceToJSON)),
    };
}

