/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosBrain } from './EquosBrain';
import {
    EquosBrainFromJSON,
    EquosBrainFromJSONTyped,
    EquosBrainToJSON,
    EquosBrainToJSONTyped,
} from './EquosBrain';

/**
 * 
 * @export
 * @interface ListEquosBrainsResponse
 */
export interface ListEquosBrainsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosBrainsResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosBrainsResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosBrainsResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosBrain>}
     * @memberof ListEquosBrainsResponse
     */
    brains: Array<EquosBrain>;
}

/**
 * Check if a given object implements the ListEquosBrainsResponse interface.
 */
export function instanceOfListEquosBrainsResponse(value: object): value is ListEquosBrainsResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('brains' in value) || value['brains'] === undefined) return false;
    return true;
}

export function ListEquosBrainsResponseFromJSON(json: any): ListEquosBrainsResponse {
    return ListEquosBrainsResponseFromJSONTyped(json, false);
}

export function ListEquosBrainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosBrainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'brains': ((json['brains'] as Array<any>).map(EquosBrainFromJSON)),
    };
}

export function ListEquosBrainsResponseToJSON(json: any): ListEquosBrainsResponse {
    return ListEquosBrainsResponseToJSONTyped(json, false);
}

export function ListEquosBrainsResponseToJSONTyped(value?: ListEquosBrainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'brains': ((value['brains'] as Array<any>).map(EquosBrainToJSON)),
    };
}

