/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosAgent } from './EquosAgent';
import {
    EquosAgentFromJSON,
    EquosAgentFromJSONTyped,
    EquosAgentToJSON,
    EquosAgentToJSONTyped,
} from './EquosAgent';

/**
 * 
 * @export
 * @interface ListEquosAgentsResponse
 */
export interface ListEquosAgentsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosAgentsResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosAgentsResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosAgentsResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosAgent>}
     * @memberof ListEquosAgentsResponse
     */
    agents: Array<EquosAgent>;
}

/**
 * Check if a given object implements the ListEquosAgentsResponse interface.
 */
export function instanceOfListEquosAgentsResponse(value: object): value is ListEquosAgentsResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('agents' in value) || value['agents'] === undefined) return false;
    return true;
}

export function ListEquosAgentsResponseFromJSON(json: any): ListEquosAgentsResponse {
    return ListEquosAgentsResponseFromJSONTyped(json, false);
}

export function ListEquosAgentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosAgentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'agents': ((json['agents'] as Array<any>).map(EquosAgentFromJSON)),
    };
}

export function ListEquosAgentsResponseToJSON(json: any): ListEquosAgentsResponse {
    return ListEquosAgentsResponseToJSONTyped(json, false);
}

export function ListEquosAgentsResponseToJSONTyped(value?: ListEquosAgentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'agents': ((value['agents'] as Array<any>).map(EquosAgentToJSON)),
    };
}

