/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EquosKnowledgeBase } from './EquosKnowledgeBase';
import {
    EquosKnowledgeBaseFromJSON,
    EquosKnowledgeBaseFromJSONTyped,
    EquosKnowledgeBaseToJSON,
    EquosKnowledgeBaseToJSONTyped,
} from './EquosKnowledgeBase';

/**
 * 
 * @export
 * @interface ListEquosKnowledgeBasesResponse
 */
export interface ListEquosKnowledgeBasesResponse {
    /**
     * 
     * @type {number}
     * @memberof ListEquosKnowledgeBasesResponse
     */
    skip: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosKnowledgeBasesResponse
     */
    take: number;
    /**
     * 
     * @type {number}
     * @memberof ListEquosKnowledgeBasesResponse
     */
    total: number;
    /**
     * 
     * @type {Array<EquosKnowledgeBase>}
     * @memberof ListEquosKnowledgeBasesResponse
     */
    items: Array<EquosKnowledgeBase>;
}

/**
 * Check if a given object implements the ListEquosKnowledgeBasesResponse interface.
 */
export function instanceOfListEquosKnowledgeBasesResponse(value: object): value is ListEquosKnowledgeBasesResponse {
    if (!('skip' in value) || value['skip'] === undefined) return false;
    if (!('take' in value) || value['take'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListEquosKnowledgeBasesResponseFromJSON(json: any): ListEquosKnowledgeBasesResponse {
    return ListEquosKnowledgeBasesResponseFromJSONTyped(json, false);
}

export function ListEquosKnowledgeBasesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEquosKnowledgeBasesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skip': json['skip'],
        'take': json['take'],
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(EquosKnowledgeBaseFromJSON)),
    };
}

export function ListEquosKnowledgeBasesResponseToJSON(json: any): ListEquosKnowledgeBasesResponse {
    return ListEquosKnowledgeBasesResponseToJSONTyped(json, false);
}

export function ListEquosKnowledgeBasesResponseToJSONTyped(value?: ListEquosKnowledgeBasesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip': value['skip'],
        'take': value['take'],
        'total': value['total'],
        'items': ((value['items'] as Array<any>).map(EquosKnowledgeBaseToJSON)),
    };
}

