/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEquosAvatarRequest
 */
export interface UpdateEquosAvatarRequest {
    /**
     * Livekit identity of the avatar.
     * @type {string}
     * @memberof UpdateEquosAvatarRequest
     */
    identity: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosAvatarRequest
     */
    name: string;
    /**
     * Base64 data URL of the reference image.
     * @type {string}
     * @memberof UpdateEquosAvatarRequest
     */
    refImage: string;
    /**
     * Optional agent ID to link with the avatar.
     * @type {object}
     * @memberof UpdateEquosAvatarRequest
     */
    agentId: object;
    /**
     * 
     * @type {object}
     * @memberof UpdateEquosAvatarRequest
     */
    client?: object;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosAvatarRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosAvatarRequest
     */
    organizationId: string;
}

/**
 * Check if a given object implements the UpdateEquosAvatarRequest interface.
 */
export function instanceOfUpdateEquosAvatarRequest(value: object): value is UpdateEquosAvatarRequest {
    if (!('identity' in value) || value['identity'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('refImage' in value) || value['refImage'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function UpdateEquosAvatarRequestFromJSON(json: any): UpdateEquosAvatarRequest {
    return UpdateEquosAvatarRequestFromJSONTyped(json, false);
}

export function UpdateEquosAvatarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEquosAvatarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'],
        'name': json['name'],
        'refImage': json['refImage'],
        'agentId': json['agentId'],
        'client': json['client'] == null ? undefined : json['client'],
        'id': json['id'],
        'organizationId': json['organizationId'],
    };
}

export function UpdateEquosAvatarRequestToJSON(json: any): UpdateEquosAvatarRequest {
    return UpdateEquosAvatarRequestToJSONTyped(json, false);
}

export function UpdateEquosAvatarRequestToJSONTyped(value?: UpdateEquosAvatarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': value['identity'],
        'name': value['name'],
        'refImage': value['refImage'],
        'agentId': value['agentId'],
        'client': value['client'],
        'id': value['id'],
        'organizationId': value['organizationId'],
    };
}

