/* tslint:disable */
/* eslint-disable */
/**
 * Equos.ai API
 * API documentation for Equos.ai live platform.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEquosCharacterRequest
 */
export interface UpdateEquosCharacterRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosCharacterRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosCharacterRequest
     */
    faceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosCharacterRequest
     */
    voiceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosCharacterRequest
     */
    brainId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosCharacterRequest
     */
    knowledgeBaseId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateEquosCharacterRequest
     */
    search?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquosCharacterRequest
     */
    elevenlabsAgentId?: string | null;
}

/**
 * Check if a given object implements the UpdateEquosCharacterRequest interface.
 */
export function instanceOfUpdateEquosCharacterRequest(value: object): value is UpdateEquosCharacterRequest {
    return true;
}

export function UpdateEquosCharacterRequestFromJSON(json: any): UpdateEquosCharacterRequest {
    return UpdateEquosCharacterRequestFromJSONTyped(json, false);
}

export function UpdateEquosCharacterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEquosCharacterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'faceId': json['faceId'] == null ? undefined : json['faceId'],
        'voiceId': json['voiceId'] == null ? undefined : json['voiceId'],
        'brainId': json['brainId'] == null ? undefined : json['brainId'],
        'knowledgeBaseId': json['knowledgeBaseId'] == null ? undefined : json['knowledgeBaseId'],
        'search': json['search'] == null ? undefined : json['search'],
        'elevenlabsAgentId': json['elevenlabsAgentId'] == null ? undefined : json['elevenlabsAgentId'],
    };
}

export function UpdateEquosCharacterRequestToJSON(json: any): UpdateEquosCharacterRequest {
    return UpdateEquosCharacterRequestToJSONTyped(json, false);
}

export function UpdateEquosCharacterRequestToJSONTyped(value?: UpdateEquosCharacterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'faceId': value['faceId'],
        'voiceId': value['voiceId'],
        'brainId': value['brainId'],
        'knowledgeBaseId': value['knowledgeBaseId'],
        'search': value['search'],
        'elevenlabsAgentId': value['elevenlabsAgentId'],
    };
}

